### ISSUE TITLE
@nivo/bar misses lodash-es as dependency

### ISSUE THREAD

**Issue by szymonmal** [plouc/nivo#114]
Hello,

I've noticed that after installing newest nivo/bar version to the clean create-react-app application and including demo Bar component from the documentation, nivo/bar misses lodash-es as dependency.

[Reproduction repo](https://github.com/szymonmal/nivo-lodash-es)

To reproduce:
1. `create-react-app application`
2. `cd application`
3. `npm i -S @nivo/bar`
4. add component code
5. `npm start` results with:

![image](https://user-images.githubusercontent.com/961649/33937658-90557e96-e004-11e7-995d-b78a7d47f212.png)

I think the issue might be in babel preset, but I'm not sure.
Adding lodash-es as a dependency to the project, or to nivo/bar package fixes this issue.

**Comment by jafp2000** [comment]
I present the same problem, i tried importing via npm but it's no works

**Comment by gioragutt** [comment]
Looking at [bar's package-json file](https://github.com/plouc/nivo/blob/master/packages/nivo-bar/package.json), it doesn't have `lodash-es` in the dependencies, so I guess that would be the fix.

**Comment by BhavyaLight** [comment]
This same is happening for @nivo/circle-packing as well

**Comment by sethbro** [comment]
Same for `@nivo/sankey`.

**Comment by brandonaaskov** [comment]
Same is true for `@nivo/calendar`.

**Comment by brandonaaskov** [comment]
I don't know nearly enough about Lerna/publishing monorepos like this, but suffice to say I can run `make package-dev-calendar` from `nivo` and then `yarn link @nivo/calendar` from my project and that _does_ work.

Best I can figure at this point is that there's something happening during the publish step since working with it in dev is fine.

**Comment by szymonmal** [comment]
Yeah, like I've mentioned in the opening post adding lodash-es as a dependency to the project, or to nivo/bar package fixes this issue, but I think that @plouc uses his own [babel-preset that changes declaration](https://github.com/plouc/nivo/blob/697e8aa59355b43d566cddd5f6a4314f30c06a71/packages/nivo-babel-preset/use-lodash-es.js). 
So like you've said @brandonaaskov running full make and linking works correctly.

**Comment by IonicaBizau** [comment]
Something similar for `@nivo/line`. `lodash@3.x.x` was loaded, but `4.x.x` was supposed to be loaded. I `npm install`ed `lodash@latest` in the root of the app and the problem didn't disappear until I manually modified the path to lodash in `compute.js` (obviously, that's not a persistent change, because it's in `node_modules`).

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/191
