### ISSUE TITLE
BarCanvas is broken

### ISSUE THREAD

**Issue by bobylito** [plouc/nivo#1273]
## Description

BarCanvas implementation is broken.

## Reproduction

https://nivo.rocks/storybook/?path=/story/barcanvas--custom-tooltip

<img width="1392" alt="Screenshot 2020-11-12 at 15 24 07" src="https://user-images.githubusercontent.com/393765/98951906-20c36680-24fb-11eb-9e99-d782c3b4b2df.png">

I'm currently trying to figure out what is exactly the issue and what could be a fix.

**Comment by wyze** [comment]
Hey, thanks for taking a look! I am betting it is because it is missing the new `valueScale` prop I added. You will need to pull it from props and add it to the options object that is passed to the generate bars functions here: https://github.com/plouc/nivo/blob/e98d8e071ae474526621761ba03d608d9a2971ec/packages/bar/src/BarCanvas.js#L106

It is where I would start anyways. :)

**Comment by bobylito** [comment]
@wyze wouah thanks for the fast answer. Definitely sounds like something I've seen in my debug session so far. 👍
