### ISSUE TITLE
Add more customizability to Pie radial label

### ISSUE THREAD

**Issue by akvashi24** [plouc/nivo#1313]
**Is your feature request related to a problem? Please describe.**
My main issue is that the radial label doesn't support `onClick` functionality

**Describe the solution you'd like**
Either a prop on `Pie` to allow onClick for radialLabel or extending the `radialLabel` prop to allow a completely custom label, similar to `Radar`

**Describe alternatives you've considered**
I have to be satisfied with clicking the slices on the pie, but it's not an alternative

**Additional context**
Happy to add an onClick function in a PR, but a completely custom radiallabel makes more sense to me

**Comment by plouc** [comment]
We're gonna be able to pass an `arcLabelsComponent` to the pie chart to completely customize the behavior/look of it once https://github.com/plouc/nivo/pull/1350 gets merged, the pie package is gonna contain some BC breaks though, several props were renamed and transitions are now supported.

You can already play with it using [this codesandbox](https://codesandbox.io/s/nivo-website-9yrvz) (which can be forked if you wish to try using it with your own setup) and the default component is available [here]( https://github.com/plouc/nivo/blob/improve-sunburst/packages/arcs/src/arc_link_labels/ArcLinkLabel.tsx).
Please note that the component is gonna receive spring values, not regular values in order to support transitions, so `react-spring` animated components should be used in lieu of regular elements.

There's also a few other improvements like the ability to grow the arcs radius on hover.
