### ISSUE TITLE
Legend `itemTextColor` no longer works 0.63+

### ISSUE THREAD

**Issue by iKrushYou** [plouc/nivo#1321]
It seems like you can no longer set the legend label colors on 0.63.0+

### 0.62.0 - legend label colors work (are white)
https://codesandbox.io/s/nivopie-typescript-forked-cclvv

### 0.63.0 - legend label colors do not work
https://codesandbox.io/s/nivopie-typescript-forked-xpk7d

**Comment by wyze** [comment]
Yes, because it reads from the theme now. So you should be able to pass something like `theme={{ textColor: null }}` to the `ThemeProvider` component, but that doesn't appear to be working either.

However, the long form works `theme={{ legends: { text: { fill: null } } }}`. But maybe we should take the `textColor` prop over the theme.

**Comment by iKrushYou** [comment]
Hey @wyze thanks for the response. I figured it wasn't some sort of deprecation because the type of script value still completed ￼
