### ISSUE TITLE
Can we put class to ResponsiveTreeMapHtml tiles to style them? 

### ISSUE THREAD

**Issue by alexnm2566** [plouc/nivo#1369]
Hello, thanks for this awesome library! 

I would like to style the tiles in ResponsiveTreeMapHtml (for ex. set border-radius), but it only puts id-s to the divs which is harder for me because I have to wait the chart to paint (and btw there's no callback for it), and only then loop through all the ids to set the style, and I would like to be able to put a unified class to all the tiles so I can style them easily.

Maybe we can put some default class to the TreeMapHtmlNode here? Is this possible? Thanks
![image](https://user-images.githubusercontent.com/58153395/103407279-8802ac00-4b77-11eb-8fa8-e7269c4d2030.png)

**Comment by alexnm2566** [comment]
OK, currently the most robust way was to just style it like this 
`& div[id^=root]` where root is just the parent object name

But it would be better to target them with some specific class

**Comment by plouc** [comment]
Hello @alexnm2566,

I avoid adding CSS classes to the charts because it's not really portable depending on the implementation (typically canvas), and would also add some extra maintenance, possibly new props.

That being said, if you really want to add CSS classes, you can also use your own `nodeComponent`, you can have a look at the [default component](https://github.com/plouc/nivo/blob/master/packages/treemap/src/TreeMapHtmlNode.js).

I do understand the advantage of having such classes, more efficient/reliable selectors, can also be useful for testing, but that's currently not in the roadmap.
