### ISSUE TITLE
Line time series axis rerender loop

### ISSUE THREAD

**Issue by LoicUV** [plouc/nivo#1379]
Render a line chart with time series on X axis. Rerender the parent component (eg useState). The X axis component enters a render loop.
I tried it with both native & string dates. Doesn't occur with a point scale.

[Codesandbox](https://codesandbox.io/s/nivo-line-graph-component-forked-3ovkf)

Looks like each `defaultTickRenderer` components of Axis is getting a new key every second.
![Capture d’écran 2021-01-07 à 12 37 36](https://user-images.githubusercontent.com/592542/103888503-272e2300-50e5-11eb-98da-7bd9b0257fa1.png)

**Comment by jamesdh** [comment]
I think I'm also experiencing this with Bar charts as well at the moment, but still digging into it.

**Comment by jamesdh** [comment]
I pushed a branch into my fork that contains a story which I believe demonstrates this issue.

Feel free to take a look: https://github.com/jamesdh/nivo/tree/bar_time_scale

**Comment by jamesdh** [comment]
Ok, please ignore my above comments. My issue is because Bar charts don't even support time scales as their "index" values.

**Comment by stephent** [comment]
I'm seeing something very similar with ResponsiveLine. It appears possibly to be a regression since version 64. If I rollback to 63.1, I don't see it.

With version 67, the line chart seems to end up in a render loop. This fires continuously sometimes from page load, sometimes after a user-initiated change that forces a chart re-render (after which it never stops):

![Screenshot 2021-01-29 at 18 43 23](https://user-images.githubusercontent.com/898090/106343688-d8972300-6263-11eb-9b60-1302f912c047.png)

These are the warnings in Chrome that caught my attention:

![Screenshot 2021-01-29 at 18 43 31](https://user-images.githubusercontent.com/898090/106343718-f9f80f00-6263-11eb-817f-d5c4f54d1d55.png)

When I revert to 63.1, and profile using React Tools, the Axes only re-render when I expect (the yellow spikes here):

![Screenshot 2021-01-29 at 18 54 47](https://user-images.githubusercontent.com/898090/106343737-1bf19180-6264-11eb-9afd-46631c77062f.png)

Let me know if there's more data I can provide or profiling that would be helpful.

**Comment by clarkd** [comment]
We are seeing the same thing, very slow performance and the axis re-rendering constantly.
