### ISSUE TITLE
Small radar charts leave blank space and are not centered

### ISSUE THREAD

**Issue by viters** [plouc/nivo#1416]
**Describe/explain the bug**
When chart is small and margins are disabled, it still does not take full available space and moreover is not centered within taken space. It does not matter whether it is Responsive or normal Radar chart.

**To Reproduce**
```
<ResponsiveRadar
  data={data}
  keys={['chardonay', 'carmenere', 'syrah']}
  indexBy="name"
  maxValue={100}
  margin={{ top: 0, right: 0, bottom: 0, left: 0 }}
  curve="linearClosed"
  borderWidth={2}
  borderColor={{ from: 'color' }}
  enableDots={false}
  gridLevels={5}
  gridShape="linear"
  colors={{ scheme: 'category10' }}
  fillOpacity={0.25}
  blendMode="multiply"
  animate={true}
  isInteractive={true}
  gridLabel={() => <></>}
  gridLabelOffset={0}
/>
```

**Expected behavior**
Radar chart takes full available space.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/13100466/107625788-2301a200-6c5d-11eb-97ca-87ea9bd72b6e.png)

With border around div:
![obraz](https://user-images.githubusercontent.com/13100466/107625856-390f6280-6c5d-11eb-8f6a-276f9852d8b8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 0.67.0

**Comment by viters** [comment]
bump

**Comment by plouc** [comment]
That's because the center is the center of the box, which is not ideal when you have 3 points only, please note that you can have a circular grid which would cover this empty space:

<img width="245" alt="Screen Shot 2021-09-06 at 22 31 10" src="https://user-images.githubusercontent.com/501642/132224966-3de2848a-d72d-4a36-8e61-06674be2b5ef.png">

@wyze, I don't think we should qualify this as a bug, and having this feature would require a bit of work, implementing this for the pie took quite some time for example and the code got quite complex, so I'm not planning to implement this at the moment, so I'm going to close this until someone wants to contribute, or this becomes a recurrent request.

For now, you can cheat and use a negative bottom margin if you want it to occupy more space, won't be responsive though, so you'll have to adjust.
