### ISSUE TITLE
Charts based on react-spring@9.0.0-rc.3 have prod issue

### ISSUE THREAD

**Issue by IvanGusak** [plouc/nivo#1453]
**Describe/explain the bug**
All charts that are using react-spring@9.0.0-rc.3 throws error on the production [Uncaught TypeError: r.willAdvance is not a function](https://github.com/pmndrs/react-spring/issues/1078)

**To Reproduce**
@nivo/line@0.67.0, 
@nivo/core@0.67.0

1. Reload the page with the chart
2. Open dev tools
4. See an error

**Desktop:**
 - Browser [e.g. chrome]

**Additional context**
I hope this information will help you to resolve the issue. Thank you for your time.

**Comment by stephanoshadjipetrou** [comment]
Just experienced the same issue and checked in react-spring repo issues to see if something similar has been reported.
As it turns out, yes - [issue](https://github.com/pmndrs/react-spring/issues/1078)

But haven't tried any of the solutions mentioned there. Hopefully someone here has any insights on how to solve this :)

**Comment by stephanoshadjipetrou** [comment]
Edit: managed to solve this with the help of this [comment](https://github.com/plouc/nivo/issues/1423)
