### ISSUE TITLE
Box-shadow on pie chart slices

### ISSUE THREAD

**Issue by Yansb** [plouc/nivo#1488]
It would be nice if we could add css properties like box shadow in this example
![image](https://user-images.githubusercontent.com/24869058/115775695-94f71580-a389-11eb-823c-4288c05324cb.png)
it could be added in themes by passing a prop slice:

**Comment by orenklein** [comment]
I'm also in need for this feature, can it be reopened?

**Comment by jeongnaehyeok** [comment]
I also need this feature too. can u open again this?

**Comment by plouc** [comment]
As it's SVG (or canvas), `box-shadow` is not supported, but a `drop-shadow()` filter would work, however it would require to either have a global ring underneath, so that the shadow doesn't overlap with other slices, or duplicating slices to prevent this (both approaches would need to support transitions).
If someone is willing to give it a try, I'd be happy to help, but that's not a priority atm.
