### ISSUE TITLE
The Tooltip of the Responsive Sunburst Chart does not appear in the latest version (0.71.0)

### ISSUE THREAD

**Issue by evabat** [plouc/nivo#1629]
It is the first time that I use these awesome components, you do a wonderful job.

However, it was impossible to make the default tooltip appear in the responsive sunburst chart.  I tried all of the given examples.
I even attempted adding custom tooltips with no luck.

It was weird because I had no issues with tooltips in the Responsive Line Chart, for example.

After downgrading to the previous version (0.70.1), it worked like a charm.

I thought that it would be useful for you to be aware of this issue :)

Thank you for your time and support.

**Comment by wyze** [comment]
Could you please provide a CodeSandbox that reproduces the issue? I am unable to reproduce it with the latest version. You can fork this as a starting template: https://codesandbox.io/s/nivo-sunburst-template-b24kg

Also, most of the time when the tooltip stops working for any chart, it is because not all nivo packages are on the same version. Please ensure you updated all charts and core to v0.71.0.

**Comment by evabat** [comment]
Yes, that was it, the difference in the version. I Installed the packages within a two days period and on the second day (release date) I got the newest version of sunburst but I did not have the same for core and line. I have updated everything and now they work fine. Thank you so much for the clarification!
