### ISSUE TITLE
Module not found nivo-arcs.es.js

### ISSUE THREAD

**Issue by juvs** [plouc/nivo#1674]
**Describe/explain the bug**
Module not found, I guess something related with locale?

**To Reproduce**
Install versión 0.72.0
Use sample pie

**Got this error:**

`./node_modules/@nivo/arcs/dist/nivo-arcs.es.js
Module not found: Can't resolve 'react/jsx-runtime' in 'D:\projects\escolastia\colegio-web-ui\node_modules\@nivo\arcs\dist'`

**Comment by joealden** [comment]
@juvs what version of `react` are you using?

The `Can't resolve 'react/jsx-runtime'` part of your error indicates to me that you are using a react version prior to `16.14.0`, as this is the earliest version that supports the "new" JSX runtime ([see here](https://github.com/facebook/react/blob/main/CHANGELOG.md#16140-october-14-2020)). The reason you are seeing this error is due to the changes made in #1612. If possible in your context, upgrading to `16.14.0` or higher should resolve the error. 

Tagging @wyze on this as this may have been an unforeseen consequence of migrating to the modern JSX runtime. It means that the minimum supported react version for `nivo` is now technically `16.14.0` (which I personally think is fine), so maybe we should update the `peerDependencies` ranges for `react` used in the repo to indicate this?

**Comment by wyze** [comment]
Ah yes, we do need to bump the peer deps. I can add some breaking changes notes to the v0.72.0 changelog/release notes.

**Comment by juvs** [comment]
> @juvs what version of `react` are you using?
> 
> The `Can't resolve 'react/jsx-runtime'` part of your error indicates to me that you are using a react version prior to `16.14.0`, as this is the earliest version that supports the "new" JSX runtime ([see here](https://github.com/facebook/react/blob/main/CHANGELOG.md#16140-october-14-2020)). The reason you are seeing this error is due to the changes made in #1612. If possible in your context, upgrading to `16.14.0` or higher should resolve the error.
> 
> Tagging @wyze on this as this may have been an unforeseen consequence of migrating to the modern JSX runtime. It means that the minimum supported react version for `nivo` is now technically `16.14.0` (which I personally think is fine), so maybe we should update the `peerDependencies` ranges for `react` used in the repo to indicate this (and add a note to the `0.72.0` release notes to highlight this)?

ver 16.10.2, for now i'm gonna back version 0.62.0 of nivo in order to review the option to update react's version. Thanks!

**Comment by iljinjung** [comment]
What version of react is nivo optimized for?

**Comment by joealden** [comment]
@iljinjung the minimum supported version is React 16.14.0, but I believe nivo is currently developed against React 17, so I'd say the more recent the React version the better.
