### ISSUE TITLE
Is there no documentation of migrations needed between versions?

### ISSUE THREAD

**Issue by vdh** [plouc/nivo#1723]
I can't locate any documentation on how to upgrade between versions of Nivo, particularly about breaking changes. The change log only has big lists of commit messages.

While trying to migrate to the latest release (from `0.62.0` to `0.73.0`), a bunch of props vanish from the components in a refactor I can't track down. Pie charts now no longer have `radialLabels*` props like `radialLabelsSkipAngle` and have been replaced by something else. But I can't find any descriptions of these refactors.

I know expecting stable APIs on anything below a 1.0 release of a library is a pipe dream, but it's really hard to make use of Nivo without at least a list of deletions / additions in the change logs when it comes to component refactors.

**Comment by plouc** [comment]
No, there's no such documentation, that's why nivo is still not 1.0, we would like to have all those refactoring done before, it's really hard for us to maintain such doc while migrating, we're basically 2 core contributors, both having jobs.

In the changelog, you can see that pie was refactored in `0.68.0`, and it lists various commits part of this refactoring, you can also find the corresponding PR here: https://github.com/plouc/nivo/pull/1331

For the available options, you can rely on the website which lists them: https://nivo.rocks/pie.
