### ISSUE TITLE
Scatter Plot render 'Custom Node' many times when data changed

### ISSUE THREAD

**Issue by Eumhongin** [plouc/nivo#1727]
![스크린샷 2021-08-23 오전 9 52 38](https://user-images.githubusercontent.com/23710025/130376899-c8646a4f-658d-4964-bd88-067090e2e585.png)
![스크린샷 2021-08-23 오전 9 52 46](https://user-images.githubusercontent.com/23710025/130376900-0fa20a93-113c-480a-b2fb-b7b38ace1b1f.png)

Hello 👋 
I have some problem in Scatter Chart.

When i render custom node with dynamic data, many times render just loading

what's going on in renderNode property in ResponsiveScatterPlot??

that code is below
![스크린샷 2021-08-23 오전 10 10 31](https://user-images.githubusercontent.com/23710025/130377074-4c788012-e6f0-4347-b3f2-b50b2328e49d.png)

**Comment by plouc** [comment]
@Eumhongin, if you have animation enabled, the node is re-rendered each time values update during transition.

Also I think you should define your component as a const, here, the component is constantly redefined as it's an inline function defined during render.

I'm currently working on migrating the package to TypeScript and migrate to `react-spring` instead of `react-motion` (see https://github.com/plouc/nivo/pull/1726), `react-spring` do not constantly update the props and use request animation frame, so this will fix this, but you should still define the component statically (outside render). I made good progress, I plan to complete the migration this week.

**Comment by Eumhongin** [comment]
@plouc So.. i can not register any events to my dot??

Or.. Data must be const? a Static data?

i understand about re rendering when data changed but when i solve make data to const, i wonder about when the event occured in dot, why re-rendering? i want a perfect example about control each dot event! 

thanks. 🌻

**Comment by plouc** [comment]
@Eumhongin, I wasn't talking about the data, I don't know how it's define given this code snippet, what I meant is that you have to define your component as a const, not as an inline function, it'll receive the props, as the default component does, so you can use events.

> i want a perfect example about control each dot event!
Sorry, but I'd suggest to look for a paid solution with paid support if that's the case, we can give directions, and sometimes more specific solutions, but you cannot expect this from open source project maintainers giving their time for free...

**Comment by plouc** [comment]
And also what I meant is that if you have animations enabled, it's normal that the node re-render during transitions, transitions animate the properties, so the component is re-rendered on each update. Please note that both this and having a component defined statically isn't specific to nivo, but how React behaves.

**Comment by Eumhongin** [comment]
@plouc Thank you about your comment and i'm sorry about double question mark 🥲  thanks!
