### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by juliomilani** [plouc/nivo#1753]
I really enjoy this tool, and after researching for some time I chose nivo as the go-to module for charts and data visualization.

One thing that bugs me is that every time we upgrade nivo's version, I have to spend a couple of hours debugging and renaming the props/attributes of the components. Although I agree that most time the renaming is for the best, I would much rather have a little inconsistency in the naming of attributes than having to modify our code every time  we need a recent feature.

Example, today I migrated from 0.67->0.73. I found the following issues:
- sliceLabel* -> arcLabel* on ResponsivePieCanvas
- radialLabel* -> arcLinkLabel* on ResponsivePieCanvas
- orient on axis object

Alternatively, a guide might be helpful.

**Comment by plouc** [comment]
I definitely agree it's inconvenient to say the least, sorry for that.

We're just 2 core maintainers with jobs, and it's hard to handle both the migration of components and creating such guides at the same time, there are a lot of big changes at the moment mostly due to the migration to TS, `react-spring` and React hooks.

That's also why nivo didn't reach v1 yet, until then, we're going to have non BC changes.

> I would much rather have a little inconsistency in the naming of attributes than having to modify our code every time we need a recent feature.

I can imagine it could be ok for you at the moment, but actually the changes in the pie package were also reflected in the sunburst package, those were renamed for consistency across other packages, which is important.

**Comment by juliomilani** [comment]
Sure. I definitely understand that.

Anyway, keep up the good work. Nivo, indeed, rocks!
