### ISSUE TITLE
[Bar] ReactDOMServer.renderToStaticMarkup doesn't render data after nivo/Bar version 0.73.0

### ISSUE THREAD

**Issue by ltimsit** [plouc/nivo#1778]
I need to convert to png multiple charts for my project, and for that i use ReactDOMServer.renderToStaticMarkup .
The issue is since nivo/bar version 0.73.0 the data are not displayed on first render even with the animate props set to false.

Here's a link to a Sandbox demo :
https://codesandbox.io/s/bar-staticmarkup-x6vzv?file=/src/App.js

If you change nivo/bar version to 0.72.0 or less the data is displayed.

Normal display and dangerouslySetInnerHTML of the staticMarkup :
![image](https://user-images.githubusercontent.com/49917451/133812241-323d644f-e2bf-4335-b780-c532e8b6cd9c.png)

**Comment by nicklas-delphai** [comment]
This is definitely still an issue in `0.79.1`. The bar chart with `renderToStaticMarkup` will only show axis and legend, but the bars all have width 0. Downgrading to `0.72` fixed the issue.

**Comment by vinismachadoo** [comment]
Any updates about this issue? PR is already closed and still can't `renderToStaticMarkup `

**Comment by tkonopka** [comment]
#1712 indeed seems to resolve the issue with missing bars. 

Given that the issue is due to animations, I checked some of the other packages (checked chord, heatmap, swarmplot). They set their initial state explicitly, and they should produce non-empty charts in ssr. 

Bar is different in that it does not set the 'initial' state at all. It is also the only package that attempts to animate during the first render, so perhaps the focus was on setting the 'from' state (?). In any case, the PR seems to be a way to support animations in the browser while also allowing ssr.

**Comment by OleksandrRakovets** [comment]
Why is it closed? It's definitely not stale and unresolved. #1712 also closed without merge, bumping it too.
