### ISSUE TITLE
[ResponsiveBar] Missing bar when there's duplicate name in data

### ISSUE THREAD

**Issue by ApolloRisky** [plouc/nivo#1779]
**Describe/explain the bug**
ResponsiveBar will appear to be completely missing a bar row when there's a duplication in `data`: two datum has same name.

**To Reproduce**
Codesandbox link: https://codesandbox.io/s/brave-mahavira-qwgro?file=/src/App.tsx

**Expected behavior**
Should show up the bar for datum which has empty-value `name`.

**Screenshots**
<img width="535" alt="Screenshot 2021-09-19 at 4 40 04 PM" src="https://user-images.githubusercontent.com/18187332/133922728-40a29a0e-b660-418e-b57d-1e8444f4277d.png">

**Desktop**
 - Browser Chrome, Safari
 - Version: @nivo/core^0.73.0, @nivo/bar^0.73.1

**Comment by plouc** [comment]
@ApolloRisky, that's the expected behavior, the x value is used as an index, and an index should be unique, it's developers' responsibility to define what they want to do with those duplicates (transforming the data to have a different index, aggregating similar index values...).
If we consider end-users, it would be quite confusing to have 2 (or more) bars corresponding to the same dimension, what does it mean? Does it includes the others, is it a bug?

**Comment by SachaG** [comment]
<img width="945" alt="Screenshot 2023-10-16 at 15 39 34" src="https://github.com/plouc/nivo/assets/358832/904ea8e6-e0a7-49d3-94c0-d58654f958a1">

I'm not sure why but for me, when two bars have the same keys (in this case the double "Job Board" bar) it's the first bar of the chart that goes missing instead.
