### ISSUE TITLE
Render order of Marker layer places text label behind other elements

### ISSUE THREAD

**Issue by jaakobls** [plouc/nivo#1782]
**Is your feature request related to a problem? Please describe.**
In the example image below ([from the storybook](https://nivo.rocks/storybook/?path=/story/line--adding-markers)) the text `x marker` is difficult to read, because it is rendered behind the lines.

**Describe alternatives you've considered**
In terms of render order of text, line, graph, it seems like the text should be rendered on top.

**Additional context**
![92331386-6B7F-4742-91E9-4307457C86EB](https://user-images.githubusercontent.com/54504952/134340276-01e4ae4b-de3e-4acf-8606-912fda7d1b45.jpeg)

**Comment by aslaksm** [comment]
The render order of layers can be changed by settings the order of the `layers` prop:
`['grid', 'markers', 'axes', 'areas', 'crosshair', 'lines', 'points', 'slices', 'mesh', 'legends']` is default,
`['grid', 'axes', 'areas', 'crosshair', 'lines', 'points', 'slices', 'mesh', 'legends', 'markers' ]`
will render the text above the line.

However, the text will still render behind any other lines in the marker layer: https://codesandbox.io/s/jovial-bose-sww3t
A workaround is to reverse the order of the marker array, since this causes the render order to reverse.

**Comment by plouc** [comment]
@jaakobls, please see @aslaksm's answer, that's how you can control the depth of layers.
