### ISSUE TITLE
Responsive charts do not resize before printing

### ISSUE THREAD

**Issue by daniharo** [plouc/nivo#1853]
**Describe/explain the bug**
When printing Nivo charts, they mantain the same width as in browser and do not scale properly.

**To Reproduce**
Open this Sandbox: https://iwxrv.csb.app/
While resizing the page width in browser, chart size is also handled automatically. However, if you print the page, chart goes off the container div (with green border) and new width is not taken into account.
This happens in all charts.
It seems that only browser without this issue is Firefox.

**Expected behavior**
When printing, charts should resize as with browser resizing.

**Screenshots**
![image](https://user-images.githubusercontent.com/47931084/145805678-a3bbb4cb-4d81-48f4-9516-8eadadbbd50e.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey, Windows 11
 - Browser: Chrome 96, Edge 96, Safari 15, **issue not happenning in** Firefox 95.

**Additional context**
Recharts library has a similar [issue](https://github.com/recharts/recharts/issues/1114), but I don't find any way to apply the workarounds suggested in that issue to Nivo charts.

**Comment by riz5034** [comment]
I'm having the same issue. I've tried using media queries and played around with using _beforeprint_ and _afterprint_, but not having any luck getting the print to resize. Were you able to figure out a solution/work around?

**Comment by daniharo** [comment]
bump

**Comment by remithomas** [comment]
@daniharo did you fix your issue ?
I'm getting the same behavior with line chart

**Comment by Gotierr** [comment]
@remithomas @daniharo Hey ! Have you managed to fix the issue ? I'have the same thing on my project. The chart have a good width but when i'm in print mode (ctrl+p), the chart just expend to the all width of the page?

**Comment by misteroh** [comment]
also having trouble here :-/

**Comment by msdrigg** [comment]
The problem is that most of these charts rely on `ResponsiveWrapper` which expands (using javascript) to fit the available space. When the print dialog opens, no javascript gets is re-run in the new printable page. This means that all the widgets show up as if the screen size being displayed is the one that was displayed before the screen printing. 

If printing is a big use case for your system, I would propose an additional possible work around of rendering 2 different pages one with `print:hidden block w-[800px]` and another with `block print:hidden` (tailwindcss notation). This way there is always a rendered printed page. This would unfortunately mean your browser/data loaders/whatnot will always have to do double the work. 

I was not able to get this to work in my use case, but it may work for others.
