### ISSUE TITLE
Custom Legend for any chart

### ISSUE THREAD

**Issue by TimTimT** [plouc/nivo#1939]
Is it possible to render legend components on any chart? 
Both for the Swarm and Bullet chart, I would like to show my users what the colors and other markings on the chart signify. 

Is there a way use the BoxLegendSvg component, feed it custom input, and render the result on a Bullet or SwarmPlot?

**Comment by tkonopka** [comment]
Legends are available for most charts, but it seems that feature is missing for swarmplot and bullet.

@TimTimT - yes, it is possible to use BoxLegendSvg to manually create a legend. See here an example with swarmplot

<img src="https://user-images.githubusercontent.com/7260190/171115866-1b332fa5-0f8d-4455-8394-7f27671285bd.png" width=250 />

https://codesandbox.io/s/clever-bash-9uxctg?file=/src/App.js

For the bullet chart, adding a legend would be more complicated because that implementation does not support custom layers. As a hack, you could create two charts side by side, the first visualizating your data, the second with an empty Bar/Swarm/Other chart and display a legend in the second adjacent chart. 

@plouc, I can add legend capability to the swarmplot. It would be nice to have that work without resorting to custom layers.

**Comment by TimTimT** [comment]
Very useful @tkonopka , Thank you!

**Comment by ppfm** [comment]
Bump

**Comment by p-abasian** [comment]
bump
