### ISSUE TITLE
Incorrect xScale/yScale types in CustomLayerProps

### ISSUE THREAD

**Issue by Idonoghue** [plouc/nivo#1947]
When defining a custom layer in Typescript the custom layer function receives an object param of the type `CustomLayerProps`. The xScale/yScale props are used as functions to pass a data value and return an x or y position. 

However the problem is that **`CustomLayerProps` defines these as `Scale` interface types, not callable function types**.

[The relevant Sandbox
](https://codesandbox.io/s/purple-fire-2l3z2s?file=/src/App.tsx)
- version 0.79.1

**Comment by pkerschbaum** [comment]
I also noticed that problem in `@nivo/line` v0.79.1.

The problem is that the types of `@nivo/scales` v0.79.0 (where `CustomLayerProps` is coming from) make use of the types of `d3-scale`, but **those types are not installed as part of any of the `@nivo/*` packages**.  
`@types/d3-scale` is defined as a devDependency in [package.json of `@nivo/scales`](https://github.com/plouc/nivo/blob/f83ad7bd26b0df489486771ac9ee28f99fff449f/packages/scales/package.json#L30), but devDependencies are not installed with the package in question (here `@nivo/scales`).

I solved it by adding `"@types/d3-scale": "3.2.2"` to my dependencies, then `CustomLayerProps` is fixed.

I do not have much experience with publishing packages which depend on types, I wonder what the long-term solution is:

1. Document that `@types/d3-scale` must be installed along the `@nivo/*` packages (if the consumer of nivo libraries uses TypeScript).
2. Define `"@types/d3-scale": "3.2.2"` in `dependencies` instead of `devDependencies` (so that it gets installed along with the nivo libraries).
3. Define `"@types/d3-scale": "3.2.2"` in `peerDependencies` instead of `devDependencies`. As of npm@7, peerDependencies are installed along with the main package, which means `@types/d3-scale` would get installed. It might be beneficial to define it as optional by configuring `peerDependenciesMeta`.

I looked at [the package.json file of `@mui/material`](https://github.com/mui/material-ui/blob/bbdf5080fc9bd9d979d657a3cb237d88b27035d9/packages/mui-material/package.json#L44-L61) and they define the types for `react` in `peerDependencies` and the types for `react-transition-group` in `dependencies` 😑.
