### ISSUE TITLE
Bar Chart Logarithmic Scale?

### ISSUE THREAD

**Issue by austenator** [plouc/nivo#1987]
**Is your feature request related to a problem? Please describe.**
We have data that requires a bar chart, and the data varies widely. Therefore need to be able to have a logarithmic yscale to better display our bar charts (since we need user to be able to hover and the bars can sometimes 'disappear' if too small compared to other data sets).

**Describe the solution you'd like**
The same logarithmic yscale-ability that the Line and ScatteredPlot components allow for.

**Describe alternatives you've considered**
I already considered using a Line chart but the way our data is separated doesn't make sense to track with a Line chart.

**Additional context**
![Screen Shot 2022-05-03 at 2 48 00 PM](https://user-images.githubusercontent.com/21992376/166563725-36c9cdb2-d66b-476e-b4af-5e946c45d073.png)

**Comment by tkonopka** [comment]
(I'm not an author/maintainer of nivo, but hope this can help)

The `Bar` component has the ability to use a log scale. See a storybook example [here](https://nivo.rocks/storybook/?path=/story/bar--with-symlog-scale) and the code [here](https://github.com/plouc/nivo/blob/master/packages/bar/stories/bar.stories.tsx#L257).

However, drawing bars on a log scale can be confusing. (An implicit assumption in a bar chart is that the amount of visible color in the bars allows a viewer to quickly compare values of adjacent bars. But a log scale puts strain on that assumption because the transformation is nonlinear and because the placement of the base of bars becomes arbitrary.)

@austenator, you mentioned considering a `Line` component to draw data points, but didn't want to see connecting lines. Here is an attempt in that direction:

https://codesandbox.io/s/damp-hill-ogl56x?file=/src/App.js

<img src="https://user-images.githubusercontent.com/7260190/166653417-51a00dc8-7117-420e-97fc-a9b11f0e08bb.png" width=540/>

This implementation uses a `Bar` component, but draws the data via a custom function (based on [BarItem](https://github.com/plouc/nivo/blob/master/packages/bar/src/BarItem.tsx)).

**Comment by austenator** [comment]
@tkonopka thanks so much for the help, this is actually exactly what I needed. I somehow missed that when looking through the docs, especially [after reading this issue.](https://github.com/plouc/nivo/issues/361#issuecomment-445853005). Now I see the Bar chart has the valueScale option of 'symlog'. 

Closing this :)
