### ISSUE TITLE
Custom color in RadialBar

### ISSUE THREAD

**Issue by nappalm** [plouc/nivo#2000]
**Describe/explain the bug**
How to add custom colors by circle item

**To Reproduce**
https://codesandbox.io/s/nivo-radia-bar-custom-color-usrbob

**Expected behavior**
Get the color of each item

**Screenshots**
![image](https://user-images.githubusercontent.com/35016608/168324676-92d8e615-4037-44e2-b6c8-f9c8e91ebdae.png)

**Comment by tkonopka** [comment]
The bars in this example are all the same color because they all represent the same category, "Vegetables". To achieve different colors, change the data object so that entries like `x: "Vegetables"` become `x: "Online"` etc.

The Bar component would also be suitable to represent this data, so you can also consider that.
