### ISSUE TITLE
Dynamically Adjust Items Shown in AxisBottom based on width of chart

### ISSUE THREAD

**Issue by robd003** [plouc/nivo#2005]
Does anyone know of a way to dynamically adjust the number of items shown in AxisBottom depending on the width of the chart?

Here's an example of a chart stretched out wider than most displays and you can see every tick:
![Screen Shot 2022-05-16 at 3 12 28 PM](https://user-images.githubusercontent.com/571328/168665713-d6f91a60-3b70-4778-bfda-2ffad67b186d.png)

Here's an example of a chart at a "normal browser width" and the X-axis is unreadable:
![Screen Shot 2022-05-16 at 3 12 17 PM](https://user-images.githubusercontent.com/571328/168665829-08663308-6e4f-4caf-b62d-a7f223241e2d.png)

I'm aware of the trick described in ticket https://github.com/plouc/nivo/issues/524#issuecomment-628296620 where you can use formatter to omit values, but is there a way to have this vary depending on the width of the chart?

Honestly I wish Nivo would just _**automatically**_ show the appropriate number of items in the X-axis.

**Comment by tkonopka** [comment]
Could it be that the chart in this example is using a categorical axis rather than a continuous one?

On a categorical axis, elements are independent entities and their positions along the axis are either accidental or a design choice. Omiting any of the labels risks losing meaning, so the chart draws all the labels even if that makes the text fragments overlap.

In the example images, it seems the values on the axis are dates. If you can turn the scale into a time scale, there will be more flexibility with the ticks on the axis. Setting `tickValues: 5`, for example, should give a small set of labels that fit without overlap. 

See [here](https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js#L152-L172) for sample code.

Admittedly, labels could still get squeezed if the display becomes even narrower.

**Comment by tkonopka** [comment]
Hi @alex20044. There are already several ways to customize the tick labels. See [here](https://nivo.rocks/storybook/?path=/story/line--time-scale) for an example. Note how there are more data points on the lines than labels on the axis, and how the labels are well-spaced and legible. 

The same approach as in the linked example can probably apply to the data in the screenshots. The key point is to set the horizontal scale to a continuous time scale (not a categorical scale). After that, my guess would be to try `tickValues: 5` to set the labels. That should suit both the narrow and the wide formats. For charts that are much smaller than in the screenshot, you can also try to display tick labels at an angle with `tickRotation` (in degrees) and `tickPadding` (in pixels).

**Comment by sebastienbarre** [comment]
> There are already several ways to customize the tick label

@tkonopka Unfortunately, this works in this example because the time scale is supported for this type of chart. Support for any form of responsible labels on the bottom axis is sorely lacking on bar charts for example.

**Comment by Glidias** [comment]
Here is something  that may not be the most optimised (uses iterative trial and error approach), but gets the job done. Wish this feature is built in within Nivo isntead of having to implement your own layers. Can try out and see if it works. Typically, you put this as a Higher order component under `renderTick:` for your manual `<Axis>`  definition within a given layer so that you can get the `innerWidth`/`innerHeight`

```
import { AxisTickProps, AxisTick } from '@nivo/axes'
import { ScaleValue } from '@nivo/scales'

interface TickUnderResponsiveAxesLayerProps extends AxisTickProps<ScaleValue> {
    innerLength: number // typically the layer's innerWidth or innerHeight, depending on the axis direction
    totalTicks: number // total number of ticks must be known beforehand  to predict the current gap size (if this isn't available, some form of dynamic value checking assuming ticks are rendered in order may be used instead to predict the existing gap based off the last rendered x coordinate, and this must be tracked on layer level instead)
    minGapDistance: number // min allowed gap distance in pixels between ticks
    alwaysShowTickLines?: boolean // whether to still preserve tick lines omitting only labels
}
const TickUnderResponsiveAxesLayer = (props: TickUnderResponsiveAxesLayerProps) => {
    const { innerLength, totalTicks, minGapDistance,
        alwaysShowTickLines = false,
        value,
        format,
        ...rest
    } = props

    let count: number | null = useMemo(() => {
        let gapSize = innerLength / totalTicks
        const gotSkips = totalTicks > 2 && gapSize < minGapDistance
        if (gotSkips) {
            let ticksToFill = totalTicks - 1

            let count = 2;
            let modifiedGapSize = gapSize;
            while (modifiedGapSize < minGapDistance) {
                modifiedGapSize = count * gapSize
                if (modifiedGapSize >= minGapDistance && Math.floor(ticksToFill / count) * count === ticksToFill) {
                    break
                }
                count++
            }
            return count
        } else return null
    }, [innerLength, minGapDistance, totalTicks])

    const isHidden = count !== null
    && totalTicks > 2 && rest.tickIndex > 0
    && rest.tickIndex < totalTicks - 1 && (rest.tickIndex % count) !== 0;

    return <g style={{visibility: !alwaysShowTickLines && isHidden ? "hidden" : undefined}}>
        <AxisTick value={isHidden ? "" : value} format={isHidden ? undefined : format}
        {...rest} />
    </g>
}

export { TickUnderResponsiveAxesLayer as ResponsiveAxisTick }

```

**Comment by blake-rouse** [comment]
We've been having this same issue. @Glidias going to try your code out and see if we can get it to work. Pretty crazy that this hasn't been implemented by NIVO yet.

**Comment by plouc** [comment]
@blake-rouse, I don't really understand what's "pretty crazy" about it. Did you try to contribute in any way to the feature?

**Comment by yairEO** [comment]
It is crazy because it is basic. contributing to source code which you did not write and barely understand, while having a demanding full-time job, is extremely difficult.

I have been tackling the problem of too-many ticks rendered for well over 100 hours.

The issue is my chart has custom bottom ticks at different distances from each other. 
Highly likely for a chart to have thousands of bottom ticks and when hovering a slice, 
it is required to show the bottom tick associated with it.

![Image](https://github.com/user-attachments/assets/b0e501db-ce81-43b3-88e9-fe670a431254)

Showing every `N` is naive and can result in ticks rendered over each other since can be many ticks and the distances aren't equal.

such a solution is out of the question.

What I did was actual measurements for every rendered tick:

1. The first tick is not overlapping other ticks (because it is the first and others are yet to exist)
2. For every consecutive tick I measure if its `x` position is overlapping with the previously-rendered tick (not all ticks are allowed to be rendered due to this described calculation). I hold an array of rendered ticks' `x` positions and check if the last-rendered tick `x` position + constant width + some gap is allowing the current tick to have enough space to render.
3. I also check if the current tick overflows from the right side of the chart.

If a tick is deemed to be hidden, it is done via CSS within the tick itself, passed as a prop, so when hovering the slices of the chart (with the mouse of course) I hide ALL the ticks and only show the tick which is associated to that hovered slice (state for the hovered slice is saved, so I know the associated "date" which matches the bottom-axis hard-coded DOM attribute)

I do this using a dynamic CSS which is inject as a `<style>` tag to the line-chart component's wrapper node.

This whole thing is an abomination of complexity which I despise and is buggy because for unknown reasons Nivo has serious issues with `renderTick` of `axisBottom` which needs to re-render but seems to sometimes isn't. Some really strange caching issues are happing with the `renderTick` function which are hidden from me and gravely affect the desired result.

```ts
// only include dates which are within the "zoom" limits
const uniqueDates = useMemo(
  () =>
    getUniqueDates(dates).filter((d: Date) => {
      const { min, max } = xScale;
      return min && max ? d >= min && d <= max : true;
    }),
  [dates, xScale]
);

const renderedTicksXArr = useRef<number[]>([]);

const axisBottom = useMemo(
  () => ({
    tickValues: uniqueDates,
    renderTick: (tickProps: AxisTickProps<Date>) => {
      const totalCount = uniqueDates.length;

      if (tickProps.x < 0) {
        return null;
      }

      if (renderedTicksXArr.current.length >= totalCount) {
        renderedTicksXArr.current.length = 0;
      }

      const tickWidth = TICK_APROX_WIDTH + TICK_PAD;

      const prevTickX =
        renderedTicksXArr.current.findLast((x) => x < tickProps.x) ??
        -tickWidth;

      const lastTickRightX = prevTickX + tickWidth;

      // rule1:only show tick if it's not overlapping with the previous tick + some padding
      const tickOverlapPreviousTick = tickProps.x < lastTickRightX;

      // rule2:only show tick if it's not overflowing to the right
      const tickOverflowsRight = tickProps.x + TICK_APROX_WIDTH > innerWidth;

      const shouldHide = tickOverlapPreviousTick || tickOverflowsRight;

      // save the last rendered tick "x" position
      if (!shouldHide) {
        renderedTicksXArr.current.push(tickProps.x);
      }

      return (
        <BottomTick
          {...tickProps}
          shouldHide={shouldHide} // hiding using "shouldHide" because it will be shown when the slice is hovered on, through CSS "!important"
          slanted={props.slotProps?.axisBottom?.slanted}
        />
      );
    },
  }),
  [
    uniqueDates,
    innerWidth,
    props.slotProps?.axisBottom?.slanted,
  ]
);
```
