### ISSUE TITLE
Data colours not applying - responsive circle packing 

### ISSUE THREAD

**Issue by MarianaK96** [plouc/nivo#2021]
**Describe/explain the bug**
I have colours assigned to each piece of data in the object I am passing in. However, some of the colours are not applying, and when I click on the data event, it shows "rgb(0, 0, 0)" (screenshot attached of this) and I have no idea where this is coming from. I thought the issue may be because my data is nested (words within word groups) but the colours _do_ word for one of the groups - the blue one. 

**To Reproduce**
As the data I use in my project is fetched via an API, I wasn't able to use the exact same data in the sandbox but I did create a shorter version and you can see it has the same problem. You can find the sanbox [here](https://codesandbox.io/s/festive-volhard-4mi9kl?file=/src/App.js).

**Expected behavior**
I expect each of the nodes to have their appropriate colour.

**Desktop (please complete the following information):**
 - OS: mac os monterey 
 - Browser: chrome 101.0.4951.64 

Thank you! And let me know if you need any other information :)

<img width="501" alt="Screenshot 2022-05-27 at 17 30 39" src="https://user-images.githubusercontent.com/77123544/170741234-530f2406-95d5-407f-8818-aa0532e9b11e.png">

<img width="881" alt="Screenshot 2022-05-27 at 17 30 50" src="https://user-images.githubusercontent.com/77123544/170741221-ad3c59db-cf41-4648-a663-c3c97073a261.png">

**Comment by tkonopka** [comment]
Hi @MarianaK96. Parts of the data in this sandbox specify colors as `rgb(R G B)` where the `R G B` values are separated by spaces. While this format is valid according to the [SVG docs](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgba), this format is not supported by [d3-color](https://github.com/d3/d3-color), which nivo uses under the hood. When those colors are used for any calculations, the end result is that the computed colors turn to `rgb(0, 0, 0, 1)`. 

One way to get around this issue is to ensure that all colors are hex strings (you already use some hex strings), or rgb strings `rgb(R, G, B)` with comma-separated values. Alternatively, because your dataset specifies colors for all your circles, you can set `inheritColorFromParent={false}`. This will turn off calculations on color values and use colors from the dataset as-is.

**Comment by plouc** [comment]
@tkonopka, thank you for investigating, [space separated values aren't supported](https://www.w3.org/TR/SVGColor12/#sRGBcolor), @MarianaK96 I'm going to close this issue, but if you're still having issues after fixing the format, please leave a comment.

**Comment by MarianaK96** [comment]
Thanks so much @tkonopka ! I can't believe that's all it was after I spent a whole day racking my brain 😅
