### ISSUE TITLE
@nivo/calendar

### ISSUE THREAD

**Issue by mikwerdna** [plouc/nivo#203]
Hi! Thanks for creating this project. It's a tremendous resource and I've enjoyed using it.

I have one small request. Would it be possible to display a single calendar year if the data only includes records for a single year? At the moment, it seems like the default is to display two calendar years and if there are no data points for the previous year, then there's just a grid with no values being displayed.

Thanks again.

**Comment by plouc** [comment]
Hi @mikwerdna!

Thank you.
You can display a single year using `from` & `to` properties. I've created a demo for this => https://codesandbox.io/s/k923r2z9m7

I close this issue as it seems to solve your need, let me know if it doesn't.

**Comment by mikwerdna** [comment]
Hi @pluoc.

Thanks for replying and thanks for taking the time to address the issue I
submitted. I tried using the from and to properties. But I ended up seeing
2 calendars years. I also see 2 calendar years displayed for that sandbox.

Best,

**Comment by plouc** [comment]
I don't understand :/

<img width="1504" alt="capture d ecran 2018-05-29 a 23 08 01" src="https://user-images.githubusercontent.com/501642/40664137-3c00cef8-6395-11e8-8e89-ce35c17a6425.png">

**Comment by mikwerdna** [comment]
That's weird. Here's what I see.

[image: ss.png]

**Comment by plouc** [comment]
@mikwerdna you must use the GitHub website to put your screenshot :)

**Comment by plouc** [comment]
@mikwerdna which browser are you using?

**Comment by mikwerdna** [comment]
@plouc Chrome (66.0.3359.181)

**Comment by tmewes** [comment]
I think he would like to have one calendar, no matter how many years this one extends. @plouc In your example, all the sample data is in 2016. If there are data for 2014 and 2015, they should also be displayed in a calendar, instead of many calendars on top of each other.

I would also find this adaptation great and would need it. ;) In my example I want to show the commits of a project in a calendar, but the commits extend over 10 years. Unfortunately, when 10 calendars are rendered on the page, the browser crashes. Maybe here would be a kind of switch (forward / backward) for the selection of the respective year the solution. Then only one calendar would be displayed and the colors and values could update when clicking on the previous / next year.

@mikwerdna Please correct me if I understood the task wrong.
If this is another issue, I can open a new one for this. :)

**Comment by plouc** [comment]
@mikwerdna, updated chrome to be on the same version, I still have a single year displayed.

**Comment by plouc** [comment]
@tmewes, pagination can be implemented, that's why `from`/`to` aren't bound to data points, this way you can set `from`/`to` to move from year to year in your dataset.

**Comment by tmewes** [comment]
@plouc Ah okay, thank you. I will try. :) @mikwerdna Sorry for my comment, I understood it wrong.

**Comment by mikwerdna** [comment]
@plouc, that's weird.

**Comment by plouc** [comment]
@tmewes, maybe this example can help: https://codesandbox.io/s/34mqv39kq1 for pagination.

**Comment by tmewes** [comment]
@plouc Awesome! Thank you very much!

**Comment by plouc** [comment]
@mikwerdna, did you tried to increase `from` and lower `to`,  just in case?

**Comment by mikwerdna** [comment]
@plouc, I just tried increasing the from prop from `2016-01-01` to `2016-02-01` and that does result in a single calendar. I tried increasing to `2016-01-02` and that results in a single calendar. Is this a `Date` issue?

**Comment by mikwerdna** [comment]
OK. Thanks for taking a look at this with me.

**Comment by antoniobologna** [comment]
This might be closed, but as a solution and for anyone having this issue, try changing the **from** property from a string to a Date. This worked for me ->

`from={new Date(new Date().getFullYear(), 0, 1)}`
