### ISSUE TITLE
Change Calendar/ResponsiveCalendar tooltip format/pattern

### ISSUE THREAD

**Issue by guilhermefarto** [plouc/nivo#213]
Hello.

I would like to know if is possible to change the format or pattern displayed in the tooltip of Calendar/ResponsiveCalendar chart

I need to display another date format for day or another information when mouse is over the cell.

![image](https://user-images.githubusercontent.com/7007095/40747809-cd48bd0e-6434-11e8-92e1-945ca75f8986.png)

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/223, you can now use the `tooltip` property to customize its content, see [website](http://nivo.rocks/calendar) & [storybook](http://nivo.rocks/storybook/?selectedKind=Calendar&selectedStory=custom%20tooltip&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) for documentation & examples. Please use `@nivo/calendar >= 0.43.0`
