### ISSUE TITLE
Range bar chart

### ISSUE THREAD

**Issue by lofsigma** [plouc/nivo#2140]
It would be great if the bar component worked with ranges.

So you could pass it data like this:
```
    const data =
        [{
            donut: [-10,10],            
            user: 'toby',
        }, {
            donut: [3,30],
            user: 'george',
        }]
```
to make a range [range bar chart](https://assets.iorbex.com/blog/wp-content/uploads/2017/11/18030314/01-Range-Bar-Example.png).

I tried using the diverging bar example to hack something together but I couldn't get it to work.

**Comment by stefanroeck** [comment]
+1
This would allow time-series barcharts like this one https://apexcharts.com/react-chart-demos/timeline-charts/basic/

**Comment by faahim** [comment]
Ah yeah! This looks like exactly what I'm trying to achieve! 

I'm trying to create a chart like this one: 

<img src="https://user-images.githubusercontent.com/21854687/220029274-5162e95d-9e38-4e78-b815-bc618f58baf8.jpg" width="50%" />

But I'm not too sure if it's doable with Nivo currently. It seemed like the diverging stacked chart will do it, but turns out, it always assumes the centre of the diverging point to be in the middle. Doesn't work well when working with time series. This is what I currently have: 

<img width="80%" alt="Screenshot 2023-02-20 at 12 34 38 PM" src="https://user-images.githubusercontent.com/21854687/220030584-1a6910a6-c187-463e-ae26-85dd1170b6f2.png">

I need to start from 10 PM and go up to 2 PM, so 0 is not the centre. Any idea if Nivo is capable of doing this? Or should I move on?

**Comment by ivan-sparq** [comment]
bump

**Comment by Zhuohui-Li** [comment]
Any update?
