### ISSUE TITLE
Modify the names of months in the Calendar

### ISSUE THREAD

**Issue by guilhermepatriarca** [plouc/nivo#217]
I want change language the calendar but only show months in English.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/223, you can now use the `monthLegend` property, see [website](http://nivo.rocks/calendar) & [storybook](http://nivo.rocks/storybook/?selectedKind=Calendar&selectedStory=translating%20months&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) for documentation & examples. Please use `@nivo/calendar >= 0.43.0`
