### ISSUE TITLE
ResponsiveBarCanvas is not plotting all data

### ISSUE THREAD

**Issue by hafeezulkareem** [plouc/nivo#2209]
**Describe/explain the bug**
I am trying to plot a bar chart using ResponsiveBarCanvas with 1000 data points. It's not plotting all the data points in the chart. We are getting one TypeError as well (e.getBBox is not a function). I am stuck with it for a long time, can you please help me with it?

**To Reproduce**
You can refer to the code in [this sandbox](https://codesandbox.io/s/nivo-bar-chart-with-large-data-bug-qegjj7).

**Expected behavior**
1. ResponsiveBarCanvas should plot the chart with all the data points. 
2. The TypeError should be resolved.

**Screenshots**
<img width="594" alt="image" src="https://user-images.githubusercontent.com/35022284/210597354-b738410d-7601-4884-9ce1-fed6b34fb2ba.png">

**Comment by tkonopka** [comment]
Hi @hafeezulkareem. 

1. The curious arrangement of bars in your screenshot comes about because your data points do not have unique identifiers. Give all your data points different "country" codes and the chart should work.

2. That error with getBBox is a know issue and has been fixed in #2125, but the fix is not yet available in a release. To avoid the error, either use `ResponsiveBar` instead of `ResponsiveBarCanvas`, or install the package from github.
