### ISSUE TITLE
Unable to stack lines with holes

### ISSUE THREAD

**Issue by maxgenest** [plouc/nivo#2250]
If I have holes in my data and stack the lines, all the lines above the one with the holes also have holes. 
What I expect as behavior is to have the lines without holes to appear even if they are above the one with holes. 

See my exemple here: https://codesandbox.io/s/practical-cray-k7dkdt?file=/src/components/line.js
In this exemple, US has no data for "plane", "helicopter", "boat", "train", "bus" and "car".
All the other countries have full data. 
We could see that Germany and Norway don't show data for the holes of US. 
I want them to show their data.

**How to reproduce:**
1. use the example given in https://nivo.rocks/line/
2. make holes in data by deleting point for US
3. ensure that you stacked the lines
4. see error

**Expected Behavior:**
I expect US to have empty points to 0 and to show the data of Germany and Norway

<img width="795" alt="Capture d’écran 2023-02-24 à 18 12 55" src="https://user-images.githubusercontent.com/12084893/221243821-ef0e0028-b492-4698-9cff-82a4de53fca2.png">

**Desktop**
 - OS: macOS 13.1
 - Browser: Brave 1.47.186 (Chromium 109.0.5414.119)

**Comment by plouc** [comment]
Stacking data while the underlying data has holes seems tricky and somehow subjective, how should the data be displayed in such a case? I chose to not handle this due to the complexity, I think for multiple series where some have holes, it's best to stick with a non stacked representation.

In your case, if empty means `0`, I'd suggest to explicitly add points with a 0 value, it should achieve what you want, and `0` has a very different meaning IMHO, holes could have any value as it's missing data.

**Comment by maxgenest** [comment]
Thank you for your answer. 

Wouldn't it be possible to admit that no data is a 0, but no data between to points with values is the same value as the previous one ? 
As in the non stacked view ?
