### ISSUE TITLE
Any blocker not to bump to last majors of d3-*?

### ISSUE THREAD

**Issue by dubzzz** [plouc/nivo#2305]
**Is your feature request related to a problem? Please describe.**

Yes and no. I observed that nivo was pulling multiple versions of some d3- packages. While trying to suggest changes to dedupe them I detected that many d3- dependencies was outdated by several majors.

**Describe the solution you'd like**

Bumping to latest major of d3-.

**Describe alternatives you've considered**

Keep it that way.

**Additional context**

Before opening any PR in that direction I wanted to confirm that it would be ok to go in that direction.

**Comment by plouc** [comment]
First, the fact that [D3 packages moved to esm](https://devclass.com/2021/06/15/d3-7-0-goes-all-in-on-ecmascript-modules/), also that D3 now requires a browser that supports ES2015. That being said, I already had to upgrade `d3-color` due to a security issue, so it would be a continuation of this update. Other than that, just the fact that D3 APIs have changed and nivo doesn't have a consistent code coverage depending on the package. We can see a summary of the changes per major [here](https://github.com/d3/d3/blob/main/CHANGES.md), and there are a few breaking changes.

**Comment by dubzzz** [comment]
Indeed the esm-only is a huge blocker : 😢

**Comment by plouc** [comment]
Yea, but I think we need to move forward anyway, other libraries relying on D3 faced the same issue, victory explained the issue in details [here](https://formidable.com/blog/2022/victory-esm/), but the infrastructure of nivo is already complex enough, I'd like to avoid to have to transpile and vendor D3 dependencies.

**Comment by plouc** [comment]
Seems like visx [is also struggling with this](https://github.com/airbnb/visx/issues/1637)...

**Comment by plouc** [comment]
I'm closing this as the main roadblock is now described in this issue: https://github.com/plouc/nivo/issues/2310.
