### ISSUE TITLE
Swarmplot nodes attaching to wrong groups when space is limited

### ISSUE THREAD

**Issue by TheMaxLin** [plouc/nivo#2335]
**Describe/explain the bug**
Swarmplot nodes may end up on the wrong group when space is limited. Increasing forceStrength fixes my specific case, but I don't think this should be needed.

**To Reproduce**
https://codesandbox.io/s/swarm-plot-bug-1i93rz?file=/src/index.js

**Expected behavior**
The nodes should always remain attached to their group.

**Screenshots**
![image](https://github.com/plouc/nivo/assets/33196529/d8f3aefc-750b-48a9-9d9f-96eb1dccd620)

**Comment by plouc** [comment]
This chart behaves this way so that we can animate nodes between groups (as it behaves in the website) it has some limitations, but as this can be fixed by adjusting the force, I don't think that's a bug, I'd like to keep the transitions, and computing the force dynamically would be difficult and inefficient.

**Comment by plouc** [comment]
Also note that rather than increasing the force, you can lower it, so that nodes stay closer to where they should be if no force was applied.
