### ISSUE TITLE
How can i fix the width of the inner chart content !!

### ISSUE THREAD

**Issue by Znoy108x** [plouc/nivo#2336]
![image](https://github.com/plouc/nivo/assets/75539409/048f0d4d-b563-48bd-b5b2-f43541a4c51c)
This is my chart and i want to fix the width of the inner chart content ,
![image](https://github.com/plouc/nivo/assets/75539409/6db0b336-4d1f-41a9-8cec-b4f588e46778)

Issue that i want to solve : 
![image](https://github.com/plouc/nivo/assets/75539409/56d1919e-7e1b-4433-8f26-efb1daa36de4)
For the data containing less number of data point the bars are overlapping on the Legends and the bar height is also large !! 

Please help me !!

**Comment by plouc** [comment]
Hi @Znoy108x,

It's a bit difficult to understand what your issue is, please use the provided issue template.
I'm going to close this for now as I cannot tell what you're trying to achieve, but feel free to open a new one with more details.

Aslo please void using double exclamation marks everywhere ;)
