### ISSUE TITLE
Nivo recipe storybook code is no longer available 

### ISSUE THREAD

**Issue by arapanbaranwal** [plouc/nivo#2365]
**Description**
So earlier I was able to see the code in the nivo storybook but it seems that it's no longer visible. 
For e.g. the recipe [Adding a metric in the center using Custom Layer](https://nivo.rocks/storybook/?path=/story/pie--adding-a-metric-in-the-center-using-a-custom-layer) had the sample code on its implementation. 

**To Reproduce**
Please go to any storybook link for e.g. https://nivo.rocks/storybook/?path=/story/pie--adding-a-metric-in-the-center-using-a-custom-layer and see there is no code to refer to. 

**Expected behavior**
When I was using nivo in April, the storybook contained the reference code for each recipe so I guess that is the expected behaviour.

**Comment by arapanbaranwal** [comment]
https://github.com/plouc/nivo/issues/434#issuecomment-889654266
As mentioned in this comment, this CenteredMetric code used to be present in the storybook.

**Comment by plouc** [comment]
@arapanbaranwal, I upgraded StoryBook to benefit from new features, the code is still available, but not from this page, it's available from https://nivo.rocks/storybook/?path=/docs/pie--docs, but it only shows the component's code, otherwise the source code for all stories is in the repo, for example: https://github.com/plouc/nivo/blob/master/storybook/stories/pie/Pie.stories.tsx#L124-L157, which is probably the best way to get the code, it's a bit less convenient, but I didn't find a better way to show the source.

**Comment by raphaelsaunier** [comment]
@plouc I'm discovering your fabulous charting library today! 🤩

The documentation site itself is beautiful, however the Storybook is hardly useful without an easy access to the source code…

While there is a “show code” button in the lower right corner, it doesn't give any additional info about how to use a given component:

![CleanShot 2024-07-16 at 10 47 41@2x](https://github.com/user-attachments/assets/a49fc727-7617-43b9-8570-5510f4c1897d)

Have you considered adding an addon such as [Storysource](https://storybook.js.org/addons/@storybook/addon-storysource)?
