### ISSUE TITLE
Line Chart `curve` crosses `min` value

### ISSUE THREAD

**Issue by source144** [plouc/nivo#2417]
**Describe/explain the bug**
The curve generated in the Line Chart goes bellow the defined `min` value.
In my use case, the data can't possibly be negative and this is misleading and seems like an error.

_Edit_:
Seems this is more a of a d3 thing. I'm not sure there's anything that can be done to bound the curve on your end.
I also noticed that with `monotoneX`, the curve is bounded.. So perhaps issue can be closed.

**To Reproduce**
CodeSandbox: https://codesandbox.io/s/nivo-line-chart-bottom-tick-values-forked-j6h6gm?file=/src/index.js

1. Reuse example code and data from https://nivo.rocks/line/
2. Set `min` value of `yScale` to `0`
3. Modify `curve` to `cardinal`
4. Modify data entries to have consecutive(?) `0` `y` values.
    1. I.e.:
  ```js
      {
        x: "train",
        y: 0
      },
      {
        x: "subway",
        y: 0
      },
```
5. Reproduced issue:

<img width="94" alt="image" src="https://github.com/plouc/nivo/assets/36644833/71686513-47ef-49e2-b756-7f34206cae75">
<br /><img width="684" alt="image" src="https://github.com/plouc/nivo/assets/36644833/c4a0cc4c-0094-401f-9da7-280ee613fa42">

<br /><br />

**Expected behavior**
Ideally the curve should not cross/overflow the defined `min` values

<br /><br />

**Comment by tkonopka** [comment]
Hi @source144. This is expected behavior given the smothing curve parameter in the chart props. In many scenarios it is desirable for curves to go a little above or below the data points, so several curve types provide that behavior. In cases with constraints (such as here), you'll have to set the interpolation type so suit your specific requirements (a min value on the axis is not enough). As you noted in the description, curve `monotoneX` preserves upper/lower bounds, so that may work for you. Other available options with that property are `linear` and the ones with `Step` as prefix.

Another possible workaround is described [here](https://github.com/plouc/nivo/issues/284#issuecomment-1680055372). (I didn't test the code, but the approach seems reasonable)

**Comment by plouc** [comment]
As @tkonopka explained, this is expected, and you have a few options to prevent this.
