### ISSUE TITLE
[Bar] Option to decide label position

### ISSUE THREAD

**Issue by evasseure** [plouc/nivo#2579]
Hello 👋 

We currently need to have the option to place the bar labels either on top (or end when horizontal) of the bars.
It seems to be something that has been asked for a few time https://github.com/plouc/nivo/issues/923 https://github.com/plouc/nivo/issues/146, and a PR has also been opened for it https://github.com/plouc/nivo/pull/1112.

So I was wondering if this is a feature you be open to receive a new PR for, or would you rather not have it implemented into Nivo, and leave it to the devs to implement their own?

It could come in the form of two new params:
- `labelPosition: "center" | "top"` (end maybe?)
- `topLabelOffset: number` (could also be merged with the recently added `totalsOffset`)

The top position would not be compatible with the stacked mode.

Cheers

**Comment by plouc** [comment]
Hello @evasseure,

I'm fine with adding this feature, but I'm working on other things atm.

I think it should be something like `'start' | 'center' | 'end'`, in order to avoid any confusion when changing the layout.
We could also leave complete freedom and support top-left, top, top-right, ... but then we would probably need 2 props to support x and y offsets, might become a bit too complex though.

On the other hand, that it's something which can be relatively easily implemented via a custom layer.

**Comment by evasseure** [comment]
Thanks for the quick feedback!
Closing now that I have opened a PR.
