### ISSUE TITLE
Really bad documentation!!! 

### ISSUE THREAD

**Issue by Fadi-Ghattas** [plouc/nivo#299]
This library seems great, but the documentation so poor even the storybook !!!!

for example:

I need to change the points colors in line chart but no clue on how to do it !!! just in the line docs 

`dotColor{string|Function}
optional | default: 'inherit'
Method to compute dots color.`

we need an example I tried 

` dotColor={(item)=> {}}` but the item is the whole object.

another thing I need to change dotSymbol also no clue just in the storybook ` dotSymbol={CustomSymbol}` what is the `CustomSymbol` you are passing ?????????

also, I need to change the tooltip content but no luck also in the doc 

`tooltip{Function}
optional | default: —
Method to create custom tooltip`

and it's not working 👎 

we need more examples and to be clear not just like  dotSymbol={CustomSymbol}` !!!!!!!!!!

**Comment by plouc** [comment]
Really bad communication, it's the first time someone open an issue in such a way.

First let me remind you that nivo is an open source project, so instead of complaining using `!` and `?` , you could for example suggest a way to improve it.

When you say the storybook is also really poor, well… that's the way the storybook works, it's not able to display nested function/elements like `CustomSymbol`, so it just prints the function name, that's not specific to nivo.

All the code for the storybook is available in the repository, [here] (https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js#L325) is the code for custom symbol and [here](https://github.com/plouc/nivo/blob/master/packages/line/stories/line.stories.js#L686) the one for custom tooltip.

Open source is not just using somebody's stuff and open (pretty impolite) issues, it's also about contributing, I'm always thankful to people offering solutions fro my problems, and I first think of what could be done to help improve the problem I had.

Maybe you should look for another library, a paid product for example, this way you'll be able to legitimately complain. I've put a big effort in the documentation, and had great feedbacks on it, so…

**Comment by gcid12** [comment]
@plouc , thanks a lot for putting together this amazing library.  Please disregard entitled people, they clearly don't understand Open Source and how everyone can improve a project.

**Comment by muhajirframe** [comment]
Yeah, have an attitude man @Fadi-Ghattas . Thanks for great work @plouc

**Comment by Fadi-Ghattas** [comment]
Hi all, not saying it's a bad library, on the contrary, it's really great one, but what I'm saying if you cloud please reveal the full power of this great lib with more examples and douc's, for example, how can I know that like plouc said  "All the code for the storybook is available in the repository, here" !!!, and I'm great full for all the Open Source projects it's makes humans life easier .

finally sorry for all who take it my words as offensive, trying to give some feedback to make this lib more usable and thanks  @plouc  for the great work.
