### ISSUE TITLE
max width for a column (Bar chart)

### ISSUE THREAD

**Issue by zhe1ka** [plouc/nivo#315]
hey, first of all, thanks for a great library :)

I create a chart bar dynamically and I don't know how many exactly there will be columns inside. This rage can be from 1 till 20. When there are 20 columns - it looks good but when there are only 1 or 2 - it doesn't look good. is it possible to have a maxWidth for columns? in docs I only found width for the whole chart which doesn't suit for my case.
Thanks)

**Comment by rpearce** [comment]
One thing that might help is the `padding` option, which can be a value between `0` and `1`. Try `padding={0.7}`!

**Comment by plouc** [comment]
Sorry but I won't add this option to the API, someone also opened an issue asking for minWidth :), but IMO padding is sufficient and you can adjust its value depending on number of bars, another (radical) option is to use a custom component for bars.

**Comment by corneliusellen** [comment]
@plouc I'm adding my plus one to adding bar width to the API. It would be really great to see this feature without having to . In my case, adjusting the padding is not a good solution because I want more space in between the bars without making them thinner.

**Comment by jeanfrancois8512** [comment]
@plouc What is the formula to calculate the padding value if I want my bar to always have a fixed widht of 22px ?

**Comment by kamilms21** [comment]
> @plouc What is the formula to calculate the padding value if I want my bar to always have a fixed widht of 22px ?

Did you find solution?

**Comment by jeanfrancois8512** [comment]
Yes, I use an other library.

Le lun. 16 août 2021 15 h 59, Kamil Kowalczyk ***@***.***> a
écrit :

**Comment by luanmm** [comment]
> Sorry but I won't add this option to the API, someone also opened an issue asking for minWidth :), but IMO padding is sufficient and you can adjust its value depending on number of bars, another (radical) option is to use a custom component for bars.

In my case, it was a rule from UX/UI team, but there are indeed some use-cases that justify creating a "maxWidth" prop for bar charts (the "minWidth" I couldn't see the point to be honest).

If anyone may need something like that, this is the way I could achieve it:

```jsx
const BAR_MAX_WIDTH = 12;

const CustomBarComponent = ({ bar: { x, y, width, height, color } }) => {
  const w = width > BAR_MAX_WIDTH ? BAR_MAX_WIDTH : width;

  return (
    <rect 
      x={x + width / 2 - w / 2} 
      y={y} 
      width={w} 
      height={height} 
      rx={Math.min(w, height) / 2} 
      fill={color} />
  );
};
```

And, of course, reference it in the chart component:

```jsx
    <ResponsiveBar
      barComponent={CustomBarComponent}
      ...
      />
```

It doesn't seem to be a complicated thing to add in the library (it may be just one line like the "w" variable calculation in my example) and there are use cases for it (sometimes by UX rules, or because we have a responsive chart changing with window resize, or because we have a dynamic number of columns and the padding option is not so trivial to calculate, and so on).

My workaround (or any need for custom components) is not a great solution, because, besides the working result, it messes up with standard behaviors (like animation).

IMHO the issue should be reopened and this option should be considered for this library.

Anyway, thanks for all the efforts regarding this library. It is a great work that the collaborators have done.

**Comment by bradlocking** [comment]
Hey all - thought i'd pop a small custom solution to supporting max-width's on bars for really simple charts. We initially went for the solution that @luanmm offered, though we also needed the max-width alongside the ability to enable default tooltips when interacting with the bar itself. nivo's `BarItem` component has all of that logic baked in, so used it, and modified the properties powering the width of the bar as overrides. 

```tsx
const CustomBarComponent = <RawDatum extends BarDatum>(props: Props<RawDatum>) => {
    const {
        bar: { data, ...bar },
        style,
    } = props;

    const w = Math.min(bar.width, BAR_MAX_WIDTH);
    const x = bar.x + bar.width / 2 - w / 2;

    const [spring, setSpring] = useSpring(() => ({
        width: w,
        transform: `translate(${x}, ${bar.y})`,
    }));

    useEffect(() => {
        setSpring({ width: w, transform: `translate(${x}, ${bar.y})` });
    }, [w, setSpring, x, bar]);

    return <BarItem {...props} bar={{ ...bar, data, x, width: w }} style={{ ...style, ...spring }} />;
};
```

Setting the width with this approach wasn't the only thing to worry about - as we also needed to make sure the bar is positioned correctly, so using react-spring to `translate` the bar itself allowed that to happen.

**Comment by meessour** [comment]
> Hey all - thought i'd pop a small custom solution to supporting max-width's on bars for really simple charts. We initially went for the solution that @luanmm offered, though we also needed the max-width alongside the ability to enable default tooltips when interacting with the bar itself. nivo's `BarItem` component has all of that logic baked in, so used it, and modified the properties powering the width of the bar as overrides.
> 
> ```tsx
> const CustomBarComponent = <RawDatum extends BarDatum>(props: Props<RawDatum>) => {
>     const {
>         bar: { data, ...bar },
>         style,
>     } = props;
> 
>     const w = Math.min(bar.width, BAR_MAX_WIDTH);
>     const x = bar.x + bar.width / 2 - w / 2;
> 
>     const [spring, setSpring] = useSpring(() => ({
>         width: w,
>         transform: `translate(${x}, ${bar.y})`,
>     }));
> 
>     useEffect(() => {
>         setSpring({ width: w, transform: `translate(${x}, ${bar.y})` });
>     }, [w, setSpring, x, bar]);
> 
>     return <BarItem {...props} bar={{ ...bar, data, x, width: w }} style={{ ...style, ...spring }} />;
> };
> ```
> 
> Setting the width with this approach wasn't the only thing to worry about - as we also needed to make sure the bar is positioned correctly, so using react-spring to `translate` the bar itself allowed that to happen.

If you have misplaced label inside the bar component you might also want to add labelX to the useSpring function like this:
```
    const [spring, setSpring] = useSpring(() => ({
        width: w,
        labelX: w / 2,
        transform: `translate(${x}, ${bar.y})`,
    }));
```

**Comment by joshi-sanjay** [comment]
Did anyone get a padding formula if they want to maintain a bar width of 20px?

**Comment by joshi-sanjay** [comment]
@plouc any formula to calculate the padding dynamically to keep the bar width fixed?

**Comment by meessour** [comment]
> @plouc any formula to calculate the padding dynamically to keep the bar width fixed?

Or how this can be achieved when using the Canvas version of the bar chart

**Comment by plouc** [comment]
I don't have a formula for this, but maybe looking at the d3 example could help defining one:  https://observablehq.com/@d3/d3-scaleband.

**Comment by joshi-sanjay** [comment]
Okay, so this is what I'm doing now to keep the `barWidth` near the specified value. It will not be fixed as the padding will always have an impact of +/- points value.
````
const [padding, setPadding] = useState<number>(0);
````

````
// Once data is loaded, calculate the padding based on the available space (this is before rendering the chart)
const groupsCount = data.length;
const barCount = groupsCount * activeLegends.length; //activeLegends is a custom legends array that keeps record of visible bars (may not be applicable to others)
const totalBarsWidth = barCount * barWidth + (barCount - groupsCount) * defaultBarValues.innerPadding;

const actualChartWidth = chartContainerRef.current?.clientWidth || 0;
const emptySpace = actualChartWidth - totalBarsWidth;
const padding = emptySpace / actualChartWidth;
setPadding(padding);
````

But this doesn't work as expected when fewer bars are rendered.
So I have to recheck it again in while rendering bars.
````
barComponent={(props) => {
    if (props.bar.width < barWidth) {
        setPadding(padding - 0.05);
            return null;
        }
        
        return (
            // Custom bar component
        );
    }
}
````

This is just a rough code and one may need to make changes as per their requirements.

**Comment by yairEO** [comment]
@plouc - I **beg** you to reconsider your verdict of closing this issue. I implore you.

I am also a maintainer of many open-source web components and know how it is like when people ask you for features but this is really basic.

Designers provide us developers with designs for **constant** bars widths - no matter the number of bars, either 1 or 2 bars or 50. doesn't matter. The UI is what the design departments dictates their desires and it's not such a big deal.

Below screenshot is from the design needs for my client and I don't want to disappoint my client by saying it cannot be done:

![image](https://github.com/user-attachments/assets/82b19015-4a5b-4ada-a6f1-d653507c8c0d)

I cannot use `padding` because this is not a serious solution when the data can be anything from a few bars to many, while the total width of the chart remains the same (many charts on the same page using the same width and should have the same bar's width)

I am begging you to please give this a second thought....🙏
