### ISSUE TITLE
Toggle charts

### ISSUE THREAD

**Issue by mhndev** [plouc/nivo#339]
Hi,
I have a chart which has 4 colored lines ,
I need to be able to toggle these lines with a button,
so when I click on green button first time it disables green line and the second time It shows it.

**Comment by plouc** [comment]
Hi @mhndev,

This is not yet supported as the legends rely on the data.
I plan to add the ability to pass data to legends without relying on it, but I don't know when I'll be able to do so, otherwise feel free to contribute ;)

Also I close this issue in favor of https://github.com/plouc/nivo/issues/196 as it's a duplicate.
