### ISSUE TITLE
Outdated version in package.json

### ISSUE THREAD

**Issue by DanielRuf** [plouc/nivo#356]
Currently I run checks with somd tools and the tools and I use pkg.version (`const pkg = require('./package.json')` but this contains 0.31, not 0.51.

So it seems it was not updated (anymore).

Would be helpful to have them in sync.

https://github.com/plouc/nivo/blob/master/package.json#L3

**Comment by DanielRuf** [comment]
Hm, seems `0.31` is from the old package and it aas forgotten to mark the old package as deprecated / outdated.

https://www.npmjs.com/package/nivo

The npm badge is from `@nivo/nivo`.

**Comment by plouc** [comment]
The version displayed on the README comes from `@nivo/core`, the main `package.json` is private so it doesn't correspond to any published package.

**Comment by plouc** [comment]
The badge is just a hint, nivo is composed of many package and not of all them have the same version.

**Comment by DanielRuf** [comment]
Well, so reading `pkg.version` is not directly possible here (just lerna.version when reading the lerna config)?

**Comment by plouc** [comment]
yes, that's the way lerna works, just out of curiosity, why do you need that? Because even reading lerna.json you'll get the latest published version for some of the packages, but for example, now it says `0.51.5`, but `@nivo/core` version is `0.51.0`. The most reliable way is to get the version from each package.

**Comment by DanielRuf** [comment]
Because we are running some code audits and creating (versioned) patches.
