### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by TxHawks** [plouc/nivo#357]
First, Thanks for this great library.

I couldn't find anything in the documentation about right-to-left support, for languages like Arabic and Hebrew.

Did I miss it? If it doesn't exist, please consider this a feature request

**Comment by pmsoltani** [comment]
Any updates on this?

**Comment by rizshivalli** [comment]
Any updates on this yet?

**Comment by kamilio** [comment]
Any plans on supporting RTL? I could help with implementation

**Comment by MuhammadSawalhy** [comment]
I think there is no need for RTL, or in my case only, I first came to this issue because I thought **nivo** needs some special way to handle RTL direction, but then I notices that I just need to make the container of the graph LTR and change the legends and axes values by formatting or just by changing the data.

![image](https://user-images.githubusercontent.com/42011920/135539374-062b0ac9-193b-44c3-b970-37759ed02cb2.png)

![image](https://user-images.githubusercontent.com/42011920/135539982-1f375e85-b9ca-421e-b0ed-c6d5c993f6c6.png)

> Notice that the direction of axes are the same (LTR), but eastern Arabic numbers and Arabic math symbols are used.

**Comment by plouc** [comment]
@MuhammadSawalhy, thank you for the information, that's interesting, I don't know any LTR language myself, but I guess I could try to setup an example, using the approach you mentioned.
