### ISSUE TITLE
time values for responsive bar canvas

### ISSUE THREAD

**Issue by DevashreeJ** [plouc/nivo#407]
I am trying to use date format for the tick values in responsive bar canvas. But I am unable to use xScale in it. It gives me an error saying "xScale does not exist on intrinsic class attributes." with react. I am using react version 15.6 and the graph works fine with mock data, however would like to use time format for this graph, and I am unable to do it.

**Comment by tj** [comment]
It seems that Bar is a bit different than Line, I ran into this as well trying to use it for timeseries data, you can do `xScale={{ type: 'time' }}` and `axisBottom={{ format: d => d.toString() }}` I believe, but `tickValues: N` doesn't work since it seems to create them per-bar.

If interested I'd be happy to send a pull-request! IIRC D3 had some nice automated scale formatting for dates as well, depending on the time range it would show years or months etc, not sure if Nivo has any of that right now.

**Comment by DevashreeJ** [comment]
Hey, thanks for the help. I did the same thing and it works fine now.

**Comment by plouc** [comment]
I've added support for time intervals, such as `tickValues="every day"` or `tickValues="every 15 minutes"`, it's only available for `@nivo/scatterplot` and `@nivo/line` though.

**Comment by plouc** [comment]
Date formatting can also be specified using `time:%Y-%m-%d` for example

**Comment by DevashreeJ** [comment]
Yea, bar is quite different. I really like the component actually, I just
had to struggle to get the ticks to behave. Works fine now.
*Thanks and Regards,*
*Devashree D. Jadhav*
*Mobile no- 3159498811*

**Comment by lanceschi** [comment]
Hi and thanks @plouc for the awesome library,

I've encountered some difficulties with time series on the xAxis. Since I'd like to keep consistency, I peek over at the [source code][1] and I ended up importing **timeFormat** in my component

```javascript
import { timeFormat } from 'd3-time-format';
```
I'd like to keep it as simple and flexible as in [@nivo/line][2] chart with:
```javascript
xScale {
  type: "time",
  format: "native"`
  ...
}
```

[1]: https://github.com/plouc/nivo/blob/master/packages/axes/src/compute.js
[2]: https://nivo.rocks/storybook/?path=/story/line--real-time-chart

**Comment by twiddler** [comment]
This issue seems to still be present.

I'd like to let `ResponsiveBar` know that the x-axis is a time scale, so that it automatically calculates a sensible amount of ticks and their positions without them overlapping.

RIght now, this is not possible. There is no way to make the x-axis of `ResponsiveBar` be a time scale. As a result, the component interprets the tick values as simple strings, and thus adds a label to each bar. This creates lots of labels that overlap if the series is long enough. The only solution I have found is to calculate the tick positions `axisBottom.tickValues` myself.

This issue has also been discussed in #283.
