### ISSUE TITLE
Add offset Axis label position 

### ISSUE THREAD

**Issue by EduardoAC** [plouc/nivo#436]
I would like to set the offset of my x-axis label so I can display between the grid lines

![xrf9m](https://user-images.githubusercontent.com/2104706/51539285-85f02880-1e4b-11e9-8db3-7183c690b30e.png)

**Comment by Tranzystor** [comment]
To move x-axis labels add negative `thickPadding` and change `layers` order:

```     <Bar
            {...commonProps}
            layers={['axes', 'grid', 'bars', 'markers', 'legends']}
            axisBottom={{
                tickPadding: lessThan,
            }}
        />
```

Does it work like you want?

**Comment by EduardoAC** [comment]
@Tranzystor that works for Bar graph, Do we have a way to do the same with line charts? I has been trying but I felt that I am missing something

**Comment by EduardoAC** [comment]
Hey! it's being 14 days, anyone could provide me some insights, how can I achieve this?

**Comment by plouc** [comment]
@EduardoAC, you can use `tickPadding` or [use custom ticks](https://nivo.rocks/storybook/?selectedKind=Bar&selectedStory=custom%20axis%20ticks&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).

You'll have to change the layers order via the `layers` property because by default axes are below the bars: `layers={['grid', 'bars', 'axes', 'markers', 'legends']}`.

**Comment by plouc** [comment]
And you can do the same for a Line chart.
