### ISSUE TITLE
ResponsiveBarCanvas ignores border width & color

### ISSUE THREAD

**Issue by stahlmanDesign** [plouc/nivo#478]
The border width / color does not work when rendering with ResponsiveBarCanvas.

You can see it's not working using the example in the docs: https://nivo.rocks/bar/canvas

Render with **ResponsiveBar** instead of **ResponsiveBarCanvas** and it works as expected.

EDIT: I see fill patterns, marker, labels, rounded rect and many other features in ResponsiveBar also do not work with ResponsiveBarCanvas. The difference is that the `borderWidth` appears to be supported in the example, but doesn't work. If not possible to support borders, it should be removed from the example.

**Comment by plouc** [comment]
Yes, as stated in the docs, some features aren't available for the canvas implementation (the same goes for all canvas based charts), however borders should be supported.

**Comment by sebastienbarre** [comment]
For those of you landing here through search, markers are not supported by `ResponsiveBarCanvas` as of the date of this comment (April 2023). You have to expand the "layers" property to see it in the docs: "The markers layer is not available in the canvas flavor.". Bummer though, because the Canvas implementation is much faster for pretty much everything.
