### ISSUE TITLE
Labels overflow on Pie chart

### ISSUE THREAD

**Issue by SammyIsra** [plouc/nivo#49]
If I have a pie chart with labels, some labels end up outside of the drawn SVG and are since not shown:
![image](https://user-images.githubusercontent.com/8962228/30040365-4f650ede-91ac-11e7-80e6-b05225f85ed9.png)
In this image, I gave the SVG tag a gray border color so it is clear what is been cut off. 

The code for the chart looks like this: 
```
<Pie 
    data={this.props.chartData}
    height={500} 
    width={500}
    margin={{
      left: 10,
      right: 50,
      top: 10,
      bottom: 10
    }}
    // not relevant other info
 />
```

**Comment by plouc** [comment]
@SammyIsra, yes, you have to add more margin to correctly display your labels, computing the required space for labels is far too costly in svg because you'll have to render the chart, compute labels size & original position, then recompute the whole chart & re-render, and this process will be invoked in each frame when animating.
