### ISSUE TITLE
treemap labels blink (or disappears late) when a node is removed

### ISSUE THREAD

**Issue by loopbender** [plouc/nivo#518]
Thank you for the great library! It really looks promising among all charting libraries.

I'm trying to use treemap component with changing data keys(identity), which means there would be nodes that are added or removed, everytime data is updated.

However, removing nodes' labels seem to have a glitching effect though.
Here is a [quick demo on codesanbox](https://codesandbox.io/s/pkjy7jmplx)

I have tried it with different components (bubble chart from circle-packing) and can confirm the bug occurs there too.

I don't know if it'd help, but decreasing the motionStiffness value actually causes the glitch effect go away but then labels disappear at the very end of animation, so it still causes an undesired view to user.

If you can lead me some path, I can dive into your awesome library to dig for a solution too.

Cheers!

**Comment by plouc** [comment]
The glitch doesn't appear in the HTML version because the divs used have `overflow: hidden`, in the SVG implementation, the rectangle is animated (width/height), but not the text, and there's a condition which prevent from rendering the node if width or height < 0, which happens because of the springy animation, typically at the end of the transition, maybe a better approach should be to animate the scale of the root `TreeMapNode` `g` element. We'll also need to keep the width/height transition, but not to use it for appear/leave.

**Comment by plouc** [comment]
https://github.com/plouc/nivo/pull/555 adds transition support for label opacity, which fixes this issue.

**Comment by royallsilwallz** [comment]
> #555 adds transition support for label opacity, which fixes this issue.

Hey plouc, I'm having the same issue. Could you please guide the steps on how to actually fix the problem? When is the next release on npm?
