### ISSUE TITLE
circle-packing zoom jank

### ISSUE THREAD

**Issue by braco** [plouc/nivo#539]
Zoom on circle-packing has much more jank than plain d3. In other words: during zoom, the same amount of rendering/bubbles produces a noticeable amount of stuttering on nivo that doesn't exist on d3.

Any idea why that is?

**Comment by plouc** [comment]
Yes, because `react-motion` uses props which force re-rendering of underlying nodes, `react-spring` could potentially improve this as it has a `native` attribute which doesn't, but it would be quite an heavy change.

Also, nivo provides pre-made components, so you've got the cost of abstractions on top of d3.

Did you noticed this on a production build or during development?

**Comment by braco** [comment]
Thank you very much for the explanation. It was production AFAIK, and is the same general environment as the d3 test, which is also paired with React... but the d3 DOM tree is kept away from React in this case.

**Comment by braco** [comment]
Why not animate the svg viewBox properties instead of all the children? This would probably speed things up tremendously.

**Comment by plouc** [comment]
@braco, the problem with this approach is that it's not compatible with HTML implementation, also, patterns, texts… won't behave the same way, I'd prefer to keep the current approach.
