### ISSUE TITLE
Bubble component

### ISSUE THREAD

**Issue by Mencls** [plouc/nivo#54]
Hello! I'm trying to find a way to group bubbles by color in the same parent so it looks like this:

![screen shot 2017-09-15 at 10 50 30 am](https://user-images.githubusercontent.com/690350/30461791-462aebda-9a04-11e7-826d-a0893e3eb889.png)

Is there an easy way to do it?

**Comment by plouc** [comment]
Hello,

Unfortunately, you want be able to get this exact result, but you have 2 other options:

#### using flat children

<img width="247" alt="capture d ecran 2017-09-15 a 12 11 22" src="https://user-images.githubusercontent.com/501642/30464909-46ae4178-9a0f-11e7-82d2-800d72fc7c05.png">

Un fortunately, you want be able to maintain adjacency using this technique.

#### using nested children

<img width="251" alt="capture d ecran 2017-09-15 a 12 11 37" src="https://user-images.githubusercontent.com/501642/30464961-8f9ef404-9a0f-11e7-94d9-03a150ad6633.png">

But you have more spacing because of the parent's enclosing bubble.

You can view those alternatives running on https://www.webpackbin.com/bins/-Ku2P3EmQvUA_LFDssjh.

**Comment by plouc** [comment]
You could have something similar using some kind of force layout with collision detection, but not easy to build IMHO :/

**Comment by Mencls** [comment]
Thanks for you reply. It confirms what I was thinking. I guess I have no choice but to go for D3 + force layout.

Great job btw, I really like this framework!

**Comment by Mencls** [comment]
@plouc Sorry I forgot I had another question. Is there an easy way to render a striped circle like this? 
![screen shot 2017-09-15 at 3 30 40 pm](https://user-images.githubusercontent.com/690350/30467837-db1b7590-9a2a-11e7-9882-c190301e9d67.png)

I've found this ```BubblePlaceholders``` component, which allows me to use ```background-image``` but according to the website example, it renders HTML. Is it doable with SVG?

**Comment by plouc** [comment]
@Mencls, nivo [supports svg patterns](http://nivo.rocks/#/guides/patterns), but not yet added to `Bubble` component, but I've started something, so expect it to be available soon enough.

**Comment by plouc** [comment]
For now, you can use `namespace="svg"` with `BubblePlaceholders`, which will use SVG instead of HTML, the doc doesn't mention it :/

**Comment by plouc** [comment]
You made me think I should add a slack or gitter chat for this kind of questions, I think it could be easier.

**Comment by plouc** [comment]
https://join.slack.com/t/nivo-dataviz/shared_invite/MjQxNzMyNzQxMTU3LTE1MDU0NTYxNjEtMTIxMGVlMzliZA

**Comment by plouc** [comment]
You can now use svg patterns with `Bubble` component.

**Comment by plouc** [comment]
Also `BubblePlaceholders` have been removed as the usage wasn't clear enough, you can now use `nodeComponent` property to fully customize node rendering (works with SVG & HTML implementations).
