### ISSUE TITLE
Stacked line graph with areaOpacity < 1 doesn't correspond to the what's being represented

### ISSUE THREAD

**Issue by cookkate** [plouc/nivo#560]
**Is your feature request related to a problem? Please describe.**
When stacked line charts have areaOpacity set to < 1, the area being filled doesn't correspond to the area represented by the data.

**Describe the solution you'd like**

The path describing the filled area should only cover the area between the lines.

**Describe alternatives you've considered**

Setting opacity to 100% solves the problem, but it would be nice to be able to be able to see the grid lines.

**Additional context**

e.g. the orange filled area overlaps the green and blue, and the green filled area overlaps the blue.

![Screen Shot 2019-05-22 at 11 44 55 AM](https://user-images.githubusercontent.com/10406459/58188795-431e5000-7c87-11e9-842a-4b5ca5f056fe.png)

It's particularly clear in cases where one of the series is very small/zero (the black series below)

![Screen Shot 2019-05-22 at 11 55 07 AM](https://user-images.githubusercontent.com/10406459/58189443-82996c00-7c88-11e9-8db8-4dbad83c4003.png)

**Comment by nylki** [comment]
It seems like the Stream-components areas are actually discrete and do not blend . It would be great to be able to have transparent discrete areas in a stacked Line component as well, without the blending/mixing.

The Stream component could be used, but it doesnt have some features I am using in the Line component.

**Comment by gavbaa** [comment]
This issue is affecting me as well, our line charts are very muddied with area fill transparency if there's more than one item visible on the chart at once.  I'm using a yScale of stacked and it looks much worse than it should.

**Comment by kir4che** [comment]
This issue still exists, the overlapping colors make the chart look not pretty.

**Comment by plouc** [comment]
It might be quite difficult to only fill the area between the lines, because lines can overlap, in several places, several times, several lines at once... That's not something I'm planning to add, if you really want to hightligth an area between some lines, you might want to consider the `Stream` chart which offers this feature as there's no overlap, it's a different kind of chart though.

**Comment by plouc** [comment]
I guess we could restrict this to the stacked mode only, which would simplify things.

**Comment by gavbaa** [comment]
It would only really make sense for stacked line graphs, for exactly the reasons you've pointed out.  We had to stop using stacked mode and moved to a different type of chart because the designers wanted the transparency more than the stacking and the multi-stack color blending made some ugly colors.  We'd go right back to stacked area charts if each stacked segment was drawn to fit, and not to the axis.
