### ISSUE TITLE
Line xScale with time type not adding ticks as expected

### ISSUE THREAD

**Issue by ConnorHome** [plouc/nivo#655]
**Describe/explain the bug**
When using `<Line xScale={{ type: 'time', precision: 'day' }} />` the ticks on the x axis are added in weird positions. I have set the axisBottom tickValues to be the length of my data array which may be an issue but even if I change it to be 10 the ticks are still in strange positions.

In the example below I have 2 values that I want to plot on the graph. Despite being 3 days apart, even if I set the tickValues to be 10 I appear to get duplicate ticks but no tick on the last result in the data.

**To Reproduce**
https://codesandbox.io/embed/mystifying-banzai-hfgie

**Expected behavior**
I would always expect the values provided in my data to have a tick (my array is already pre-filtered so it will only ever deliver one score per day).

In the example provided I would expect there to be a `Aug 02` tick.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: 75

**Comment by wyze** [comment]
I always have to add `useUTC: false` to the `xScale` and it does seem to fix it in this case as well.

**Comment by ConnorHome** [comment]
@wyze you are right, `useUTC: false` does fix this instance but a simple change to the data set appears to confuse things again.

Forked example here: https://codesandbox.io/embed/sweet-cohen-1ehz7
I have added `useUTC: false` to the `xScale` but changed the first data point to be a day earlier.

**Comment by wyze** [comment]
I think the problem is now there is a decent gap in your data, but you tell nivo that you only want 2 tick values, so it does exactly that.

I have a similar graph where I had to do something custom based on the data length because nivo was being crazy with it's tick values.

```ts
  const dataLength = data[0].data.length
  const tickValues =
    dataLength < 5
      ? data[0].data.map(({ x }) => new Date(x, 0))
      : `every ${Math.round(dataLength / 10)} year`
```

My data is on year instead of day, but it would be similar. I noticed if there was less than 5 data points it would generate points that didn't make sense, so I passed points from my data.
