### ISSUE TITLE
Line Y-axis overlap

### ISSUE THREAD

**Issue by Slither8** [plouc/nivo#660]
Hey @plouc ! Thank you for this great library! The performance is really really great!!
However, I experience a similar problem but with the line chart. As you can see in the image below, I dynamically set min and max on the x-axis (time-based, varies according to user selection) which causes the line and the x-axis to overlap. Is there any fix for this which I just couldn't find yet? If not, could you give me a hint on how and where to implement an option to enable/disable this behavior? Of course I'd be willing to share the code/create a PR if it fits your needs as well.
![image](https://user-images.githubusercontent.com/6223247/62307640-3d619980-b484-11e9-958c-9dddcdb25bdf.png)

Thank you in advance!!

P.S. Setting min/max for the x-axis is not part of the documentation but works - except for the overlap - really well!

**Comment by plouc** [comment]
@Slither8, in fact is only used to compute the scale, but doesn't clamp values, that's probably something that could be added.

**Comment by trepidacious** [comment]
I need to implement zooming (e.g. via drawing a box), so as a first step I was looking at setting the scale on both axes and ran into this issue.

I had two questions:

1. Can I rely on setting min/max for the x-axis, or might it stop working since it is not documented?
2. As a short-term fix, could the line series use a clipPath? I've tried this by manually adding a clipPath to the generated elements in Chrome tools, and modifying the path elements to reference this, and it works well. I would imagine this might have performance implications, but visually at least it looks fine.

**Comment by wyze** [comment]
> Can I rely on setting min/max for the x-axis, or might it stop working since it is not documented?

I don't see this changing.

**Comment by bmwebster** [comment]
@wyze Thanks, that's great, I'll proceed with using it for zooming. Does the approach to fixing the overlap issue using a `clipPath` or a nested `<svg>` make sense?

**Comment by bmwebster** [comment]
Bump - any interest in the pull request to clip outside the data area? This could always be a non-default option.
