### ISSUE TITLE
Combined stacked bar with line chart

### ISSUE THREAD

**Issue by MatheusPopp** [plouc/nivo#678]
Is it possible to build a stacked bar with a line chart? Like a composed chart? If isn't, is there any plan to build this feature on the future?

**Comment by airhorns** [comment]
👍 for this feature -- it's a genuinely common need in data visualization! It poses some uncomfortable questions for the nivo React API because it seems like most components "own" the whole charting surface as opposed to compose all nice. Recharts has a bunch of much smaller grained components so that it can support these composed charts, but, the API is much lower level because of that.

**Comment by MatheusPopp** [comment]
@airhorns  i've tried recharts too, but the component Composed Chart didn't work with stacked bar and line charts, just work with normal bar and line. Have you ever tried on rechart stacked bar with line?

**Comment by taschetto** [comment]
This is much needed in nivo. Unfortunately I'm using Recharts for this, but I'd love to change it for a nivo  implementation.

**Comment by GeekOnCoffee** [comment]
I've found https://codesandbox.io/s/91l6kj5wop on another issue, but it only gets you part of the way.

**Comment by fftristan** [comment]
Hi. What if I wanted to use { ResponsiveLine } from '@nivo/line' and have a Bar component as one of the layers to the ResponsiveLine? These bar and line combination sandbox examples are great (https://codesandbox.io/s/m4ro13jjn8?file=/src/index.js, https://codesandbox.io/s/91l6kj5wop), but I am actually looking for kinda the opposite of those examples: I would like to build around the the ResponsiveLine as opposed to the Bar because I prefer the tooltip/crosshairs of the ResponsiveLine. Basically what I am aiming for is the line component makes up a running total, while the bars as each additional amount, added up equal that total (line over bars). I don't need a tooltip/crosshairs for the bar component. Any ideas on how I can add a bar layer or a d3-shape layer to the line components that is pretty straightforward? Thanks for any help!

**Comment by RealAdamSinger** [comment]
Yeah it would be nice to see a proper way to impliment this. 
I am not exactly sure exactly what the differences between the bar and line components are but what seems like the simple approach to me is to start with the [line series example](https://nivo.rocks/line) and just add an option to render a series as a bar. 
This would essentially have all the functionality of the line chart but be rendered as a bar.

**Comment by RealAdamSinger** [comment]
@plouc would it be possible to retrofit the `generateVerticalStackedBars` logic into `layers` in a line chart?

**Comment by nigellima** [comment]
> I've found https://codesandbox.io/s/91l6kj5wop on another issue, but it only gets you part of the way.

Do you know how to make it work using Name values in the `x` attribute? In this example, the x values are numbers as strings. when I change it to name keys (like 'cars') the xScale returns undefined

**Comment by Michael-Xie** [comment]
Any updates to this feature? I think this would be very useful for data viz.

**Comment by felipeblobo** [comment]
Somebody has news?
