### ISSUE TITLE
bug: tickValues are not working when using it on axisRight ResponsiveBar

### ISSUE THREAD

**Issue by knackjax** [plouc/nivo#85]
I wanted to specify different values for the left and right axes. When doing so, all the custom values are appearing at the top right position.

Example: https://www.webpackbin.com/bins/-KyIZNDisQjTeGdcceL2

Thanks

**Comment by plouc** [comment]
That's because the Y axis ticks are computed using `id` in your case, and the values you pass for right axis aren't valid values for the computed scale, so there's no way to figure out where to put them.

**Comment by plouc** [comment]
Ok, I think I got it, in fact you want to display the id of each bar on left axis and corresponding value on the right, am I right?
Won't work with the tickValues options because values do not fit the computed scale.
I figured out how to do it using axis `format` option instead, this way the position is correct, a little bit hacky, but it works => https://www.webpackbin.com/bins/-Kyl5-cvUaOqMG58qgIT

**Comment by knackjax** [comment]
Yes you got it right. Thanks this is exactly what I was looking for!  On another note it would be nice to be able to adjust the labels in the bars (text-align: right) rather than default center. I would not need the right axis if that is an option.
