### ISSUE TITLE
TypeError: Cannot read property 'animate' of undefined

### ISSUE THREAD

**Issue by diegosps** [plouc/nivo#985]
**Describe/explain the bug**
Mixing packages bar and pie throws this error when trying to render bar chart.

I was using the `"@nivo/pie": "^0.61.1",` without any problems.
But today when I tried to use the bar chart, I started receiving this error:
```
TypeError: Cannot read property 'animate' of undefined
Axis
node_modules/@nivo/axes/dist/nivo-axes.esm.js:314
  311 |     legendOffset = _ref2.legendOffset,
  312 |     onClick = _ref2.onClick;
  313 | var theme = useTheme();
> 314 | var _useMotionConfig = useMotionConfig(),
      | ^  315 |     animate = _useMotionConfig.animate,
  316 |     springConfig = _useMotionConfig.springConfig;
  317 | var formatValue = useMemo(function () {
```

This might be related to https://github.com/plouc/nivo/issues/603 but since there is not description there of how to reproduce and it is closed, I'm opening this new issue.

**To Reproduce**
I don't think this can be reproduced on code sandbox because it looks like a problem with package dependencies.

1.`npm i @nivo/pie` (When I did this, It was 0.61.1)
2. 
```
import { ResponsivePie } from '@nivo/pie'
import { categoricalColorSchemes } from '@nivo/colors'
```
3. All works fine
4. `npm i @nivo/bar` (This installed 0.62.0)
5. `import { ResponsiveBar } from '@nivo/bar'`
6. The error is thrown whenever I try to render ResponsiveBar

To "fix":

1. `npm un @nivo/pie`
2. A new error occur: `Module not found: Can't resolve '@nivo/colors' in 'C:\...'`
3. `npm un @nivo/bar`
4. `npm i @nivo/bar`
5. The bar chart now works fine
6. `npm i @nivo/pie` (Now it installed 0.62.0)
7. All charts works fine now

**Expected behavior**
"Minor" versions of charts shouldn't break other charts and force a complete reinstall of all nivo packages.

Thanks for the library!

**Comment by plouc** [comment]
@diegosps, even minor package versions needs to be aligned for now, that's why it's not a V1 yet, so even minor versions might break other charts, we try to keep the exposed API backward compatible most of the time, but internals might change.
We're progressively moving from recompose to the hooks API, and we would also like to move to TS and replace react-motion with react-spring, this should not change the API too much, but we'd like to achieve this before creating a V1.
I'm gonna add an entry to the FAQ to explain this limitation.
I hope everything now works as expected and that you didn't have to change your existing Pie chart.

**Comment by diegosps** [comment]
I didn't know this pre v1 behavior, sorry for the issue then.
Didn't have to change it at all. Just update the references.
Thanks!

**Comment by plouc** [comment]
Yes, it's not documented 😅, which is definitely an issue and should be written down somewhere.
